// Búsqueda con IA en otros idiomas sin IA externa: las palabras clave de cada idioma
// se cambian por las españolas y después se usa el intérprete local de siempre.
// Cada línea: «palabras|alternativas = español». Las frases largas van antes que las cortas.

const RULES = {
  en: `holiday rentals|holiday rental|vacation rentals|vacation rental|holiday apartments|holiday apartment|apartments|apartment|aparthotel|flats|flat|studios|studio = apartamento
holiday homes|holiday home|vacation homes|vacation home|holiday houses|holiday house|villas|villa|cottages|cottage|chalets|chalet|cabins|cabin|country houses|country house = villa
youth hostels|youth hostel|hostels|hostel|guesthouses|guesthouse|guest houses|guest house = hostal
the canary islands|canary islands|the canaries|canaries = canarias
the balearic islands|balearic islands|balearics = baleares
andalusia = andalucia
catalonia = cataluna
all inclusive|all-inclusive = todo incluido
full board = pension completa
half board = media pension
bed and breakfast|breakfast included|with breakfast|breakfast = desayuno
adults only|adults-only|adult only = solo adultos
beachfront|on the beach|by the sea|sea front|seafront = primera linea
air conditioning|air-conditioned|air conditioned|aircon = aire acondicionado
airport transfer|airport shuttle|shuttle = traslado
pet friendly|pet-friendly|dog friendly|dog-friendly|pets|pet|dogs|dog = mascota
best rated|top rated|highest rated|best reviews|best reviewed = mejor valorado
non-stop|nonstop|direct|without stops = directo
one stop|1 stop|one stopover|one layover|one connection = una escala
stopovers|stopover|layovers|layover|connections|connecting|stops = escalas
less than|cheaper than|under|below|up to|max|maximum|no more than = menos de
city break = escapada urbana
weekend = fin de semana
nights|night = noches
weeks|week = semana
days|day = dias
flights|flight|fly|plane = vuelos
cheap|cheapest|budget|low cost|affordable = barato
luxury|luxurious = lujo
beach|seaside = playa
mountains|mountain = montaña
skiing|ski = esqui
romantic|honeymoon = romantica
couple = pareja
family|families|kids|children|child = niños
nature|countryside|rural|hiking = naturaleza
culture|museums|museum|history = cultura
nightlife|party = fiesta
food|gastronomy = gastronomia
stars|star = estrellas
pool|swimming pool = piscina
heating = calefaccion
gym|fitness = gimnasio
restaurant = restaurante
wheelchair|accessible = accesible
euros|euro|eur = euros
january = enero
february = febrero
march = marzo
april = abril
may = mayo
june = junio
july = julio
august = agosto
september = septiembre
october = octubre
november = noviembre
december = diciembre
one|a = una
two = dos
three = tres
four = cuatro
five = cinco
six = seis
seven = siete
ten = diez
from = desde
to = a
in|at = en
for = para
with = con`,
  fr: `locations de vacances|location de vacances|locations saisonnières|location saisonnière|appartements|appartement|studios|studio|résidence de tourisme|appart'hôtel|apparthotel = apartamento
maisons de vacances|maison de vacances|gîtes|gîte|gites|gite|villas|villa|chalets|chalet = villa
auberges de jeunesse|auberge de jeunesse|hostels|hostel = hostal
îles canaries|iles canaries|canaries = canarias
îles baléares|iles baleares|baléares|baleares = baleares
andalousie = andalucia
catalogne = cataluna
all inclusive|tout compris|tout inclus = todo incluido
pension complète = pension completa
demi-pension|demi pension = media pension
petit-déjeuner|petit déjeuner = desayuno
réservé aux adultes|adultes uniquement|adultes seulement = solo adultos
pieds dans l'eau|bord de mer|front de mer|sur la plage = primera linea
climatisation|climatisé|climatisée = aire acondicionado
navette aéroport|transfert aéroport|navette = traslado
animaux acceptés|animaux|animal|chiens|chien = mascota
les mieux notés|mieux notés|mieux noté|meilleures notes = mejor valorado
sans escale|direct|directs = directo
une escale|1 escale = una escala
escales|escale|correspondances|correspondance = escalas
moins de|moins cher que|maximum|max|jusqu'à = menos de
week-end|weekend = fin de semana
nuits|nuit = noches
semaines|semaine = semana
jours|jour = dias
vols|vol|avion = vuelos
pas cher|pas chère|pas chers|bon marché|économique|petit budget = barato
luxe|luxueux = lujo
plage|mer = playa
montagne = montaña
ski = esqui
romantique|lune de miel = romantica
famille|familles|enfants|enfant = niños
nature|campagne = naturaleza
culture|musées|musée = cultura
fête|soirée = fiesta
gastronomie = gastronomia
étoiles|étoile = estrellas
piscine = piscina
chauffage = calefaccion
salle de sport|fitness = gimnasio
restaurant = restaurante
accessible|fauteuil roulant = accesible
janvier = enero
février = febrero
mars = marzo
avril = abril
mai = mayo
juin = junio
juillet = julio
août = agosto
septembre = septiembre
octobre = octubre
novembre = noviembre
décembre = diciembre
une|un = una
deux = dos
trois = tres
quatre = cuatro
cinq = cinco
six = seis
sept = siete
dix = diez
depuis = desde
à|au|aux = a
dans = en
pour = para
avec = con`,
  de: `ferienwohnungen|ferienwohnung|ferienapartments|ferienapartment|apartments|apartment|appartements|appartement|wohnungen|wohnung = apartamento
ferienhäuser|ferienhaus|villen|villa|chalets|chalet|landhäuser|landhaus|hütten|hütte = villa
jugendherbergen|jugendherberge|hostels|hostel|pensionen|pension|gästehäuser|gästehaus = hostal
kanarischen inseln|kanarische inseln|kanaren = canarias
balearischen inseln|balearen = baleares
andalusien = andalucia
katalonien = cataluna
berghotels|berghotel = hotel montaña
wochenendtrip|wochenendausflug|wochenendreise = escapada fin de semana
romantischer|romantischen = romantica
all inclusive|all-inclusive = todo incluido
vollpension = pension completa
halbpension = media pension
mit frühstück|frühstück = desayuno
nur für erwachsene|nur erwachsene = solo adultos
direkt am strand|direkt am meer|am strand|am meer|strandnah = primera linea
klimaanlage|klimatisiert = aire acondicionado
flughafentransfer|transfer|shuttle = traslado
haustierfreundlich|haustiere|haustier|hunde|hund = mascota
am besten bewertet|bestbewertet|beste bewertungen = mejor valorado
direktflüge|direktflug = vuelos directos
nonstop|ohne umstieg|direkt = directo
einem umstieg|ein umstieg|einem stopp|einem zwischenstopp = una escala
umstiegen|umstieg|zwischenstopps|zwischenstopp|anschlussflug = escalas
weniger als|unter|maximal|höchstens|bis zu|bis = menos de
wochenende = fin de semana
nächte|nacht|übernachtungen|übernachtung = noches
wochen|woche = semana
tage|tag = dias
flüge|flug|fliegen|flugzeug = vuelos
günstig|günstige|günstigen|billig|preiswert = barato
luxus|luxuriös = lujo
strand|meer = playa
berge|gebirge = montaña
skifahren|ski = esqui
romantisch|romantische|romantisches|flitterwochen = romantica
familie|familien|kindern|kinder|kind = niños
natur|wandern = naturaleza
kultur|museen|museum = cultura
party|nachtleben = fiesta
essen|gastronomie = gastronomia
sternen|sterne|stern = estrellas
schwimmbad|pool = piscina
heizung = calefaccion
parkplatz|parken = parking
fitnessstudio|fitness = gimnasio
restaurant = restaurante
barrierefrei|rollstuhl = accesible
januar = enero
februar = febrero
märz = marzo
april = abril
mai = mayo
juni = junio
juli = julio
august = agosto
september = septiembre
oktober = octubre
november = noviembre
dezember = diciembre
eine|einen|ein = una
zwei = dos
drei = tres
vier = cuatro
fünf = cinco
sechs = seis
sieben = siete
zehn = diez
von|ab = desde
nach = a
in|im = en
für = para
mit = con`,
  it: `case vacanza|casa vacanza|appartamenti|appartamento|monolocali|monolocale|residence|aparthotel = apartamento
villa|ville|agriturismi|agriturismo|chalet|baite|baita = villa
ostelli|ostello|affittacamere = hostal
isole canarie|canarie = canarias
isole baleari|baleari = baleares
andalusia = andalucia
catalogna = cataluna
all inclusive|tutto incluso = todo incluido
pensione completa = pension completa
mezza pensione = media pension
colazione inclusa|con colazione|colazione = desayuno
solo adulti = solo adultos
fronte mare|sulla spiaggia|sul mare = primera linea
aria condizionata|climatizzato|climatizzata = aire acondicionado
navetta aeroportuale|transfer aeroportuale|navetta|transfer = traslado
animali ammessi|animali domestici|animali|cani|cane = mascota
più votati|meglio recensiti|migliori recensioni|migliori = mejor valorado
senza scali|senza scalo|diretto|diretti = directo
uno scalo|1 scalo = una escala
scali|scalo|coincidenze = escalas
meno di|massimo|max|fino a|sotto = menos de
fine settimana|weekend = fin de semana
notti|notte = noches
settimane|settimana = semana
giorni|giorno = dias
voli|volo|aereo = vuelos
economico|economici|economica|low cost|conveniente = barato
lusso|lussuoso = lujo
spiaggia|mare = playa
montagna = montaña
sci = esqui
romantica|romantico|luna di miele = romantica
famiglia|famiglie|bambini|bambino = niños
natura|campagna = naturaleza
cultura|musei|museo = cultura
festa|vita notturna = fiesta
gastronomia|cibo = gastronomia
stelle|stella = estrellas
piscina = piscina
riscaldamento = calefaccion
parcheggio = parking
palestra = gimnasio
ristorante = restaurante
accessibile|sedia a rotelle = accesible
gennaio = enero
febbraio = febrero
marzo = marzo
aprile = abril
maggio = mayo
giugno = junio
luglio = julio
agosto = agosto
settembre = septiembre
ottobre = octubre
novembre = noviembre
dicembre = diciembre
una|uno|un = una
due = dos
tre = tres
quattro = cuatro
cinque = cinco
sei = seis
sette = siete
dieci = diez
da|dal|dalla = desde
in = en
per = para
con = con`,
  pt: `alojamento local|apartamentos|apartamento|estúdios|estúdio|aparthotel = apartamento
casas de férias|casa de férias|moradias|moradia|vivendas|vivenda|villas|villa|chalés|chalé|turismo rural = villa
hostels|hostel|albergues|albergue|guest houses|guest house = hostal
ilhas canárias|canárias|canarias = canarias
ilhas baleares|baleares = baleares
andaluzia = andalucia
catalunha = cataluna
tudo incluído|tudo incluido|all inclusive = todo incluido
pensão completa = pension completa
meia pensão|meia-pensão = media pension
pequeno-almoço|pequeno almoço|café da manhã = desayuno
só adultos|apenas adultos|só para adultos = solo adultos
frente ao mar|à beira-mar|beira-mar|na praia = primera linea
ar condicionado = aire acondicionado
transfer do aeroporto|transfer|traslado = traslado
aceitam animais|animais de estimação|animais|cães|cão = mascota
mais bem avaliados|melhor avaliados|melhores avaliações = mejor valorado
sem escalas|sem escala|direto|diretos = directo
uma escala|1 escala = una escala
escalas|escala|conexões|conexão = escalas
menos de|máximo|até|abaixo de = menos de
fim de semana = fin de semana
noites|noite = noches
semanas|semana = semana
dias|dia = dias
voos|voo|avião = vuelos
barato|baratos|barata|económico|econômico|low cost = barato
luxo|luxuoso = lujo
praia|mar = playa
montanha|serra = montaña
esqui = esqui
romântica|romântico|lua de mel = romantica
família|famílias|crianças|criança|filhos = niños
natureza|campo = naturaleza
cultura|museus|museu = cultura
festa|vida noturna = fiesta
gastronomia|comida = gastronomia
estrelas|estrela = estrellas
piscina = piscina
aquecimento = calefaccion
estacionamento|parque de estacionamento = parking
ginásio = gimnasio
restaurante = restaurante
acessível|cadeira de rodas = accesible
janeiro = enero
fevereiro = febrero
março = marzo
abril = abril
maio = mayo
junho = junio
julho = julio
agosto = agosto
setembro = septiembre
outubro = octubre
novembro = noviembre
dezembro = diciembre
uma|um = una
dois|duas = dos
três = tres
quatro = cuatro
cinco = cinco
seis = seis
sete = siete
dez = diez
em|no|na = en
com = con`,
  nl: `vakantiewoningen|vakantiewoning|vakantiehuizen|vakantiehuis|villa's|villa|chalets|chalet|bungalows|bungalow = villa
appartementen|appartement|studio's|studio|aparthotel = apartamento
jeugdherbergen|jeugdherberg|hostels|hostel|pensions|pension = hostal
canarische eilanden = canarias
balearen = baleares
andalusië|andalusie = andalucia
catalonië|catalonie = cataluna
berghotels|berghotel = hotel montaña
weekendje weg|weekendje = escapada fin de semana
all inclusive|all-inclusive = todo incluido
volpension = pension completa
halfpension = media pension
met ontbijt|ontbijt inbegrepen|ontbijt = desayuno
alleen volwassenen|alleen voor volwassenen = solo adultos
aan het strand|aan zee|direct aan zee = primera linea
airconditioning|airco = aire acondicionado
luchthavenvervoer|transfer|shuttle = traslado
huisdiervriendelijk|huisdieren|huisdier|honden|hond = mascota
best beoordeelde|best beoordeeld|hoogst gewaardeerde = mejor valorado
zonder overstap|rechtstreekse|rechtstreeks|directe|direct = directo
één overstap|een overstap|1 overstap = una escala
overstappen|overstap|tussenstops|tussenstop = escalas
minder dan|onder|maximaal|hoogstens|tot = menos de
weekend = fin de semana
nachten|nacht = noches
weken|week = semana
dagen|dag = dias
vluchten|vlucht|vliegen|vliegtuig = vuelos
goedkoop|goedkope|voordelig|budget = barato
luxe|luxueus = lujo
strand|zee = playa
bergen|gebergte = montaña
skiën|ski = esqui
romantisch|romantische|huwelijksreis = romantica
gezin|gezinnen|kinderen|kind = niños
natuur|platteland = naturaleza
cultuur|musea|museum = cultura
feest|uitgaan = fiesta
eten|gastronomie = gastronomia
sterren|ster = estrellas
zwembad = piscina
verwarming = calefaccion
parkeerplaats|parkeren = parking
sportschool|fitness = gimnasio
restaurant = restaurante
rolstoel|toegankelijk = accesible
januari = enero
februari = febrero
maart = marzo
april = abril
mei = mayo
juni = junio
juli = julio
augustus = agosto
september = septiembre
oktober = octubre
november = noviembre
december = diciembre
één|een = una
twee = dos
drie = tres
vier = cuatro
vijf = cinco
zes = seis
zeven = siete
tien = diez
van|vanuit = desde
naar = a
in = en
voor = para
met = con`,
};

const compiled = {};
for (const [lang, text] of Object.entries(RULES)) {
  compiled[lang] = text.split('\n').map((line) => {
    const [words, es] = line.split('=').map((x) => x.trim());
    const alts = words.split('|').map((w) => w.trim().replace(/[.*+?^${}()[\]\\]/g, '\\$&').replace(/ /g, '\\s+'));
    return [new RegExp(`(?<![\\p{L}\\p{N}])(?:${alts.join('|')})(?![\\p{L}\\p{N}])`, 'giu'), es];
  });
}

// «cheap beach hotel in Gandía for a week» → «barato playa hotel en Gandía para una semana».
export function toSpanish(text, lang) {
  let out = String(text);
  // En portugués «para» es «a» delante de un sitio («de Lisboa para Madrid»).
  if (lang === 'pt') out = out.replace(/(?<![\p{L}])para\s+(?=\p{Lu})/gu, 'a ');
  for (const [re, es] of compiled[lang] || []) out = out.replace(re, es);
  return out;
}
