// Destinos para las páginas de buscadores (hoteles y vuelos), con su nombre en cada idioma.
// type: 'beach' (costa/playa), 'island', 'city', 'mountain' (montaña/esquí/rural).
// iata: aeropuerto principal que sirve el destino (null si no tiene uno razonable cerca).
// Si varias ciudades comparten iata, la primera de la lista es la dueña del aeropuerto.
export const CITIES = [
  // España
  { es: 'Madrid', en: 'Madrid', fr: 'Madrid', de: 'Madrid', it: 'Madrid', pt: 'Madrid', nl: 'Madrid', country: 'ES', type: 'city', iata: 'MAD' },
  { es: 'Barcelona', en: 'Barcelona', fr: 'Barcelone', de: 'Barcelona', it: 'Barcellona', pt: 'Barcelona', nl: 'Barcelona', country: 'ES', type: 'city', iata: 'BCN' },
  { es: 'Valencia', en: 'Valencia', fr: 'Valence', de: 'Valencia', it: 'Valencia', pt: 'Valência', nl: 'Valencia', country: 'ES', type: 'city', iata: 'VLC' },
  { es: 'Sevilla', en: 'Seville', fr: 'Séville', de: 'Sevilla', it: 'Siviglia', pt: 'Sevilha', nl: 'Sevilla', country: 'ES', type: 'city', iata: 'SVQ' },
  { es: 'Málaga', en: 'Málaga', fr: 'Malaga', de: 'Málaga', it: 'Malaga', pt: 'Málaga', nl: 'Málaga', country: 'ES', type: 'city', iata: 'AGP' },
  { es: 'Palma de Mallorca', en: 'Palma de Mallorca', fr: 'Palma de Majorque', de: 'Palma de Mallorca', it: 'Palma di Maiorca', pt: 'Palma de Maiorca', nl: 'Palma de Mallorca', country: 'ES', type: 'island', iata: 'PMI' },
  { es: 'Alicante', en: 'Alicante', fr: 'Alicante', de: 'Alicante', it: 'Alicante', pt: 'Alicante', nl: 'Alicante', country: 'ES', type: 'beach', iata: 'ALC' },
  { es: 'Granada', en: 'Granada', fr: 'Grenade', de: 'Granada', it: 'Granada', pt: 'Granada', nl: 'Granada', country: 'ES', type: 'city', iata: 'GRX' },
  { es: 'Bilbao', en: 'Bilbao', fr: 'Bilbao', de: 'Bilbao', it: 'Bilbao', pt: 'Bilbau', nl: 'Bilbao', country: 'ES', type: 'city', iata: 'BIO' },
  { es: 'Tenerife', en: 'Tenerife', fr: 'Tenerife', de: 'Teneriffa', it: 'Tenerife', pt: 'Tenerife', nl: 'Tenerife', country: 'ES', type: 'island', iata: 'TFS' },
  { es: 'Gran Canaria', en: 'Gran Canaria', fr: 'Grande Canarie', de: 'Gran Canaria', it: 'Gran Canaria', pt: 'Grã Canária', nl: 'Gran Canaria', country: 'ES', type: 'island', iata: 'LPA' },
  { es: 'Ibiza', en: 'Ibiza', fr: 'Ibiza', de: 'Ibiza', it: 'Ibiza', pt: 'Ibiza', nl: 'Ibiza', country: 'ES', type: 'island', iata: 'IBZ' },
  { es: 'Mallorca', en: 'Majorca', fr: 'Majorque', de: 'Mallorca', it: 'Maiorca', pt: 'Maiorca', nl: 'Mallorca', country: 'ES', type: 'island', iata: 'PMI' },
  { es: 'Menorca', en: 'Menorca', fr: 'Minorque', de: 'Menorca', it: 'Minorca', pt: 'Minorca', nl: 'Menorca', country: 'ES', type: 'island', iata: 'MAH' },
  { es: 'Lanzarote', en: 'Lanzarote', fr: 'Lanzarote', de: 'Lanzarote', it: 'Lanzarote', pt: 'Lanzarote', nl: 'Lanzarote', country: 'ES', type: 'island', iata: 'ACE' },
  { es: 'Fuerteventura', en: 'Fuerteventura', fr: 'Fuerteventura', de: 'Fuerteventura', it: 'Fuerteventura', pt: 'Fuerteventura', nl: 'Fuerteventura', country: 'ES', type: 'island', iata: 'FUE' },
  { es: 'Córdoba', en: 'Córdoba', fr: 'Cordoue', de: 'Córdoba', it: 'Cordova', pt: 'Córdova', nl: 'Córdoba', country: 'ES', type: 'city', iata: null },
  { es: 'Jerez de la Frontera', en: 'Jerez de la Frontera', fr: 'Jerez de la Frontera', de: 'Jerez de la Frontera', it: 'Jerez de la Frontera', pt: 'Jerez de la Frontera', nl: 'Jerez de la Frontera', country: 'ES', type: 'city', iata: 'XRY' },
  { es: 'Cádiz', en: 'Cádiz', fr: 'Cadix', de: 'Cádiz', it: 'Cadice', pt: 'Cádis', nl: 'Cádiz', country: 'ES', type: 'beach', iata: 'XRY' },
  { es: 'San Sebastián', en: 'San Sebastián', fr: 'Saint-Sébastien', de: 'San Sebastián', it: 'San Sebastián', pt: 'San Sebastián', nl: 'San Sebastián', country: 'ES', type: 'beach', iata: 'EAS' },
  { es: 'Santander', en: 'Santander', fr: 'Santander', de: 'Santander', it: 'Santander', pt: 'Santander', nl: 'Santander', country: 'ES', type: 'beach', iata: 'SDR' },
  { es: 'Oviedo', en: 'Oviedo', fr: 'Oviedo', de: 'Oviedo', it: 'Oviedo', pt: 'Oviedo', nl: 'Oviedo', country: 'ES', type: 'city', iata: 'OVD' },
  { es: 'Gijón', en: 'Gijón', fr: 'Gijón', de: 'Gijón', it: 'Gijón', pt: 'Gijón', nl: 'Gijón', country: 'ES', type: 'beach', iata: 'OVD' },
  { es: 'A Coruña', en: 'A Coruña', fr: 'La Corogne', de: 'A Coruña', it: 'La Coruña', pt: 'Corunha', nl: 'A Coruña', country: 'ES', type: 'city', iata: 'LCG' },
  { es: 'Santiago de Compostela', en: 'Santiago de Compostela', fr: 'Saint-Jacques-de-Compostelle', de: 'Santiago de Compostela', it: 'Santiago di Compostela', pt: 'Santiago de Compostela', nl: 'Santiago de Compostela', country: 'ES', type: 'city', iata: 'SCQ' },
  { es: 'Vigo', en: 'Vigo', fr: 'Vigo', de: 'Vigo', it: 'Vigo', pt: 'Vigo', nl: 'Vigo', country: 'ES', type: 'city', iata: 'VGO' },
  { es: 'Zaragoza', en: 'Zaragoza', fr: 'Saragosse', de: 'Saragossa', it: 'Saragozza', pt: 'Saragoça', nl: 'Zaragoza', country: 'ES', type: 'city', iata: 'ZAZ' },
  { es: 'Murcia', en: 'Murcia', fr: 'Murcie', de: 'Murcia', it: 'Murcia', pt: 'Múrcia', nl: 'Murcia', country: 'ES', type: 'city', iata: 'RMU' },
  { es: 'Almería', en: 'Almería', fr: 'Almería', de: 'Almería', it: 'Almería', pt: 'Almeria', nl: 'Almería', country: 'ES', type: 'beach', iata: 'LEI' },
  { es: 'Salamanca', en: 'Salamanca', fr: 'Salamanque', de: 'Salamanca', it: 'Salamanca', pt: 'Salamanca', nl: 'Salamanca', country: 'ES', type: 'city', iata: null },
  { es: 'Toledo', en: 'Toledo', fr: 'Tolède', de: 'Toledo', it: 'Toledo', pt: 'Toledo', nl: 'Toledo', country: 'ES', type: 'city', iata: null },
  { es: 'Segovia', en: 'Segovia', fr: 'Ségovie', de: 'Segovia', it: 'Segovia', pt: 'Segóvia', nl: 'Segovia', country: 'ES', type: 'city', iata: null },
  { es: 'Girona', en: 'Girona', fr: 'Gérone', de: 'Girona', it: 'Girona', pt: 'Girona', nl: 'Girona', country: 'ES', type: 'city', iata: 'GRO' },
  { es: 'Reus', en: 'Reus', fr: 'Reus', de: 'Reus', it: 'Reus', pt: 'Reus', nl: 'Reus', country: 'ES', type: 'city', iata: 'REU' },
  { es: 'Tarragona', en: 'Tarragona', fr: 'Tarragone', de: 'Tarragona', it: 'Tarragona', pt: 'Tarragona', nl: 'Tarragona', country: 'ES', type: 'beach', iata: 'REU' },
  { es: 'Castellón de la Plana', en: 'Castellón de la Plana', fr: 'Castellón de la Plana', de: 'Castellón de la Plana', it: 'Castellón de la Plana', pt: 'Castellón de la Plana', nl: 'Castellón de la Plana', country: 'ES', type: 'city', iata: 'CDT' },
  { es: 'Benidorm', en: 'Benidorm', fr: 'Benidorm', de: 'Benidorm', it: 'Benidorm', pt: 'Benidorm', nl: 'Benidorm', country: 'ES', type: 'beach', iata: 'ALC' },
  { es: 'Marbella', en: 'Marbella', fr: 'Marbella', de: 'Marbella', it: 'Marbella', pt: 'Marbella', nl: 'Marbella', country: 'ES', type: 'beach', iata: 'AGP' },
  { es: 'Torremolinos', en: 'Torremolinos', fr: 'Torremolinos', de: 'Torremolinos', it: 'Torremolinos', pt: 'Torremolinos', nl: 'Torremolinos', country: 'ES', type: 'beach', iata: 'AGP' },
  { es: 'Benalmádena', en: 'Benalmádena', fr: 'Benalmádena', de: 'Benalmádena', it: 'Benalmádena', pt: 'Benalmádena', nl: 'Benalmádena', country: 'ES', type: 'beach', iata: 'AGP' },
  { es: 'Fuengirola', en: 'Fuengirola', fr: 'Fuengirola', de: 'Fuengirola', it: 'Fuengirola', pt: 'Fuengirola', nl: 'Fuengirola', country: 'ES', type: 'beach', iata: 'AGP' },
  { es: 'Estepona', en: 'Estepona', fr: 'Estepona', de: 'Estepona', it: 'Estepona', pt: 'Estepona', nl: 'Estepona', country: 'ES', type: 'beach', iata: 'AGP' },
  { es: 'Nerja', en: 'Nerja', fr: 'Nerja', de: 'Nerja', it: 'Nerja', pt: 'Nerja', nl: 'Nerja', country: 'ES', type: 'beach', iata: 'AGP' },
  { es: 'Mijas', en: 'Mijas', fr: 'Mijas', de: 'Mijas', it: 'Mijas', pt: 'Mijas', nl: 'Mijas', country: 'ES', type: 'beach', iata: 'AGP' },
  { es: 'Gandía', en: 'Gandia', fr: 'Gandia', de: 'Gandia', it: 'Gandia', pt: 'Gandia', nl: 'Gandia', country: 'ES', type: 'beach', iata: 'VLC' },
  { es: 'Cullera', en: 'Cullera', fr: 'Cullera', de: 'Cullera', it: 'Cullera', pt: 'Cullera', nl: 'Cullera', country: 'ES', type: 'beach', iata: 'VLC' },
  { es: 'Dénia', en: 'Dénia', fr: 'Dénia', de: 'Dénia', it: 'Dénia', pt: 'Dénia', nl: 'Dénia', country: 'ES', type: 'beach', iata: 'ALC' },
  { es: 'Jávea', en: 'Jávea', fr: 'Jávea', de: 'Jávea', it: 'Jávea', pt: 'Jávea', nl: 'Jávea', country: 'ES', type: 'beach', iata: 'ALC' },
  { es: 'Calpe', en: 'Calpe', fr: 'Calpe', de: 'Calpe', it: 'Calpe', pt: 'Calpe', nl: 'Calpe', country: 'ES', type: 'beach', iata: 'ALC' },
  { es: 'Altea', en: 'Altea', fr: 'Altea', de: 'Altea', it: 'Altea', pt: 'Altea', nl: 'Altea', country: 'ES', type: 'beach', iata: 'ALC' },
  { es: 'Torrevieja', en: 'Torrevieja', fr: 'Torrevieja', de: 'Torrevieja', it: 'Torrevieja', pt: 'Torrevieja', nl: 'Torrevieja', country: 'ES', type: 'beach', iata: 'ALC' },
  { es: 'Santa Pola', en: 'Santa Pola', fr: 'Santa Pola', de: 'Santa Pola', it: 'Santa Pola', pt: 'Santa Pola', nl: 'Santa Pola', country: 'ES', type: 'beach', iata: 'ALC' },
  { es: 'Elche', en: 'Elche', fr: 'Elche', de: 'Elche', it: 'Elche', pt: 'Elche', nl: 'Elche', country: 'ES', type: 'city', iata: 'ALC' },
  { es: 'Peñíscola', en: 'Peñíscola', fr: 'Peñíscola', de: 'Peñíscola', it: 'Peñíscola', pt: 'Peñíscola', nl: 'Peñíscola', country: 'ES', type: 'beach', iata: 'CDT' },
  { es: 'Benicasim', en: 'Benicàssim', fr: 'Benicàssim', de: 'Benicàssim', it: 'Benicàssim', pt: 'Benicàssim', nl: 'Benicàssim', country: 'ES', type: 'beach', iata: 'CDT' },
  { es: 'Salou', en: 'Salou', fr: 'Salou', de: 'Salou', it: 'Salou', pt: 'Salou', nl: 'Salou', country: 'ES', type: 'beach', iata: 'REU' },
  { es: 'Cambrils', en: 'Cambrils', fr: 'Cambrils', de: 'Cambrils', it: 'Cambrils', pt: 'Cambrils', nl: 'Cambrils', country: 'ES', type: 'beach', iata: 'REU' },
  { es: 'Sitges', en: 'Sitges', fr: 'Sitges', de: 'Sitges', it: 'Sitges', pt: 'Sitges', nl: 'Sitges', country: 'ES', type: 'beach', iata: 'BCN' },
  { es: 'Lloret de Mar', en: 'Lloret de Mar', fr: 'Lloret de Mar', de: 'Lloret de Mar', it: 'Lloret de Mar', pt: 'Lloret de Mar', nl: 'Lloret de Mar', country: 'ES', type: 'beach', iata: 'GRO' },
  { es: 'Tossa de Mar', en: 'Tossa de Mar', fr: 'Tossa de Mar', de: 'Tossa de Mar', it: 'Tossa de Mar', pt: 'Tossa de Mar', nl: 'Tossa de Mar', country: 'ES', type: 'beach', iata: 'GRO' },
  { es: 'Blanes', en: 'Blanes', fr: 'Blanes', de: 'Blanes', it: 'Blanes', pt: 'Blanes', nl: 'Blanes', country: 'ES', type: 'beach', iata: 'GRO' },
  { es: 'Roses', en: 'Roses', fr: 'Roses', de: 'Roses', it: 'Roses', pt: 'Roses', nl: 'Roses', country: 'ES', type: 'beach', iata: 'GRO' },
  { es: 'Playa de Aro', en: 'Platja d\'Aro', fr: 'Platja d\'Aro', de: 'Platja d\'Aro', it: 'Platja d\'Aro', pt: 'Platja d\'Aro', nl: 'Platja d\'Aro', country: 'ES', type: 'beach', iata: 'GRO' },
  { es: 'Cadaqués', en: 'Cadaqués', fr: 'Cadaqués', de: 'Cadaqués', it: 'Cadaqués', pt: 'Cadaqués', nl: 'Cadaqués', country: 'ES', type: 'beach', iata: 'GRO' },
  { es: 'Cartagena', en: 'Cartagena', fr: 'Carthagène', de: 'Cartagena', it: 'Cartagena', pt: 'Cartagena', nl: 'Cartagena', country: 'ES', type: 'city', iata: 'RMU' },
  { es: 'La Manga del Mar Menor', en: 'La Manga del Mar Menor', fr: 'La Manga del Mar Menor', de: 'La Manga del Mar Menor', it: 'La Manga del Mar Menor', pt: 'La Manga del Mar Menor', nl: 'La Manga del Mar Menor', country: 'ES', type: 'beach', iata: 'RMU' },
  { es: 'Águilas', en: 'Águilas', fr: 'Águilas', de: 'Águilas', it: 'Águilas', pt: 'Águilas', nl: 'Águilas', country: 'ES', type: 'beach', iata: 'RMU' },
  { es: 'Roquetas de Mar', en: 'Roquetas de Mar', fr: 'Roquetas de Mar', de: 'Roquetas de Mar', it: 'Roquetas de Mar', pt: 'Roquetas de Mar', nl: 'Roquetas de Mar', country: 'ES', type: 'beach', iata: 'LEI' },
  { es: 'Mojácar', en: 'Mojácar', fr: 'Mojácar', de: 'Mojácar', it: 'Mojácar', pt: 'Mojácar', nl: 'Mojácar', country: 'ES', type: 'beach', iata: 'LEI' },
  { es: 'Tarifa', en: 'Tarifa', fr: 'Tarifa', de: 'Tarifa', it: 'Tarifa', pt: 'Tarifa', nl: 'Tarifa', country: 'ES', type: 'beach', iata: 'XRY' },
  { es: 'Conil de la Frontera', en: 'Conil de la Frontera', fr: 'Conil de la Frontera', de: 'Conil de la Frontera', it: 'Conil de la Frontera', pt: 'Conil de la Frontera', nl: 'Conil de la Frontera', country: 'ES', type: 'beach', iata: 'XRY' },
  { es: 'Chiclana de la Frontera', en: 'Chiclana de la Frontera', fr: 'Chiclana de la Frontera', de: 'Chiclana de la Frontera', it: 'Chiclana de la Frontera', pt: 'Chiclana de la Frontera', nl: 'Chiclana de la Frontera', country: 'ES', type: 'beach', iata: 'XRY' },
  { es: 'Zahara de los Atunes', en: 'Zahara de los Atunes', fr: 'Zahara de los Atunes', de: 'Zahara de los Atunes', it: 'Zahara de los Atunes', pt: 'Zahara de los Atunes', nl: 'Zahara de los Atunes', country: 'ES', type: 'beach', iata: 'XRY' },
  { es: 'El Puerto de Santa María', en: 'El Puerto de Santa María', fr: 'El Puerto de Santa María', de: 'El Puerto de Santa María', it: 'El Puerto de Santa María', pt: 'El Puerto de Santa María', nl: 'El Puerto de Santa María', country: 'ES', type: 'beach', iata: 'XRY' },
  { es: 'Sanlúcar de Barrameda', en: 'Sanlúcar de Barrameda', fr: 'Sanlúcar de Barrameda', de: 'Sanlúcar de Barrameda', it: 'Sanlúcar de Barrameda', pt: 'Sanlúcar de Barrameda', nl: 'Sanlúcar de Barrameda', country: 'ES', type: 'beach', iata: 'XRY' },
  { es: 'Isla Cristina', en: 'Isla Cristina', fr: 'Isla Cristina', de: 'Isla Cristina', it: 'Isla Cristina', pt: 'Isla Cristina', nl: 'Isla Cristina', country: 'ES', type: 'beach', iata: 'SVQ' },
  { es: 'Santa Cruz de Tenerife', en: 'Santa Cruz de Tenerife', fr: 'Santa Cruz de Tenerife', de: 'Santa Cruz de Tenerife', it: 'Santa Cruz de Tenerife', pt: 'Santa Cruz de Tenerife', nl: 'Santa Cruz de Tenerife', country: 'ES', type: 'island', iata: 'TFN' },
  { es: 'Puerto de la Cruz', en: 'Puerto de la Cruz', fr: 'Puerto de la Cruz', de: 'Puerto de la Cruz', it: 'Puerto de la Cruz', pt: 'Puerto de la Cruz', nl: 'Puerto de la Cruz', country: 'ES', type: 'island', iata: 'TFN' },
  { es: 'Costa Adeje', en: 'Costa Adeje', fr: 'Costa Adeje', de: 'Costa Adeje', it: 'Costa Adeje', pt: 'Costa Adeje', nl: 'Costa Adeje', country: 'ES', type: 'island', iata: 'TFS' },
  { es: 'Los Cristianos', en: 'Los Cristianos', fr: 'Los Cristianos', de: 'Los Cristianos', it: 'Los Cristianos', pt: 'Los Cristianos', nl: 'Los Cristianos', country: 'ES', type: 'island', iata: 'TFS' },
  { es: 'Playa de las Américas', en: 'Playa de las Américas', fr: 'Playa de las Américas', de: 'Playa de las Américas', it: 'Playa de las Américas', pt: 'Playa de las Américas', nl: 'Playa de las Américas', country: 'ES', type: 'island', iata: 'TFS' },
  { es: 'Las Palmas de Gran Canaria', en: 'Las Palmas de Gran Canaria', fr: 'Las Palmas de Grande Canarie', de: 'Las Palmas de Gran Canaria', it: 'Las Palmas de Gran Canaria', pt: 'Las Palmas de Grã Canária', nl: 'Las Palmas de Gran Canaria', country: 'ES', type: 'island', iata: 'LPA' },
  { es: 'Maspalomas', en: 'Maspalomas', fr: 'Maspalomas', de: 'Maspalomas', it: 'Maspalomas', pt: 'Maspalomas', nl: 'Maspalomas', country: 'ES', type: 'island', iata: 'LPA' },
  { es: 'Playa del Inglés', en: 'Playa del Inglés', fr: 'Playa del Inglés', de: 'Playa del Inglés', it: 'Playa del Inglés', pt: 'Playa del Inglés', nl: 'Playa del Inglés', country: 'ES', type: 'island', iata: 'LPA' },
  { es: 'Puerto del Carmen', en: 'Puerto del Carmen', fr: 'Puerto del Carmen', de: 'Puerto del Carmen', it: 'Puerto del Carmen', pt: 'Puerto del Carmen', nl: 'Puerto del Carmen', country: 'ES', type: 'island', iata: 'ACE' },
  { es: 'Costa Teguise', en: 'Costa Teguise', fr: 'Costa Teguise', de: 'Costa Teguise', it: 'Costa Teguise', pt: 'Costa Teguise', nl: 'Costa Teguise', country: 'ES', type: 'island', iata: 'ACE' },
  { es: 'Playa Blanca', en: 'Playa Blanca', fr: 'Playa Blanca', de: 'Playa Blanca', it: 'Playa Blanca', pt: 'Playa Blanca', nl: 'Playa Blanca', country: 'ES', type: 'island', iata: 'ACE' },
  { es: 'Corralejo', en: 'Corralejo', fr: 'Corralejo', de: 'Corralejo', it: 'Corralejo', pt: 'Corralejo', nl: 'Corralejo', country: 'ES', type: 'island', iata: 'FUE' },
  { es: 'La Palma', en: 'La Palma', fr: 'La Palma', de: 'La Palma', it: 'La Palma', pt: 'La Palma', nl: 'La Palma', country: 'ES', type: 'island', iata: 'SPC' },
  { es: 'La Gomera', en: 'La Gomera', fr: 'La Gomera', de: 'La Gomera', it: 'La Gomera', pt: 'La Gomera', nl: 'La Gomera', country: 'ES', type: 'island', iata: 'GMZ' },
  { es: 'El Hierro', en: 'El Hierro', fr: 'El Hierro', de: 'El Hierro', it: 'El Hierro', pt: 'El Hierro', nl: 'El Hierro', country: 'ES', type: 'island', iata: 'VDE' },
  { es: 'Alcúdia', en: 'Alcúdia', fr: 'Alcúdia', de: 'Alcúdia', it: 'Alcúdia', pt: 'Alcúdia', nl: 'Alcúdia', country: 'ES', type: 'island', iata: 'PMI' },
  { es: 'Magaluf', en: 'Magaluf', fr: 'Magaluf', de: 'Magaluf', it: 'Magaluf', pt: 'Magaluf', nl: 'Magaluf', country: 'ES', type: 'island', iata: 'PMI' },
  { es: 'Pollença', en: 'Pollença', fr: 'Pollença', de: 'Pollença', it: 'Pollença', pt: 'Pollença', nl: 'Pollença', country: 'ES', type: 'island', iata: 'PMI' },
  { es: 'Sóller', en: 'Sóller', fr: 'Sóller', de: 'Sóller', it: 'Sóller', pt: 'Sóller', nl: 'Sóller', country: 'ES', type: 'island', iata: 'PMI' },
  { es: 'Cala Millor', en: 'Cala Millor', fr: 'Cala Millor', de: 'Cala Millor', it: 'Cala Millor', pt: 'Cala Millor', nl: 'Cala Millor', country: 'ES', type: 'island', iata: 'PMI' },
  { es: 'Cala d\'Or', en: 'Cala d\'Or', fr: 'Cala d\'Or', de: 'Cala d\'Or', it: 'Cala d\'Or', pt: 'Cala d\'Or', nl: 'Cala d\'Or', country: 'ES', type: 'island', iata: 'PMI' },
  { es: 'Sant Antoni de Portmany', en: 'Sant Antoni de Portmany', fr: 'Sant Antoni de Portmany', de: 'Sant Antoni de Portmany', it: 'Sant Antoni de Portmany', pt: 'Sant Antoni de Portmany', nl: 'Sant Antoni de Portmany', country: 'ES', type: 'island', iata: 'IBZ' },
  { es: 'Santa Eulalia del Río', en: 'Santa Eulària des Riu', fr: 'Santa Eulària des Riu', de: 'Santa Eulària des Riu', it: 'Santa Eulària des Riu', pt: 'Santa Eulària des Riu', nl: 'Santa Eulària des Riu', country: 'ES', type: 'island', iata: 'IBZ' },
  { es: 'Formentera', en: 'Formentera', fr: 'Formentera', de: 'Formentera', it: 'Formentera', pt: 'Formentera', nl: 'Formentera', country: 'ES', type: 'island', iata: 'IBZ' },
  { es: 'Mahón', en: 'Mahón', fr: 'Mahón', de: 'Mahón', it: 'Mahón', pt: 'Mahón', nl: 'Mahón', country: 'ES', type: 'island', iata: 'MAH' },
  { es: 'Ciudadela', en: 'Ciutadella', fr: 'Ciutadella', de: 'Ciutadella', it: 'Ciutadella', pt: 'Ciutadella', nl: 'Ciutadella', country: 'ES', type: 'island', iata: 'MAH' },
  { es: 'Hondarribia', en: 'Hondarribia', fr: 'Hondarribia', de: 'Hondarribia', it: 'Hondarribia', pt: 'Hondarribia', nl: 'Hondarribia', country: 'ES', type: 'beach', iata: 'EAS' },
  { es: 'Zarautz', en: 'Zarautz', fr: 'Zarautz', de: 'Zarautz', it: 'Zarautz', pt: 'Zarautz', nl: 'Zarautz', country: 'ES', type: 'beach', iata: 'EAS' },
  { es: 'Santillana del Mar', en: 'Santillana del Mar', fr: 'Santillana del Mar', de: 'Santillana del Mar', it: 'Santillana del Mar', pt: 'Santillana del Mar', nl: 'Santillana del Mar', country: 'ES', type: 'city', iata: 'SDR' },
  { es: 'Comillas', en: 'Comillas', fr: 'Comillas', de: 'Comillas', it: 'Comillas', pt: 'Comillas', nl: 'Comillas', country: 'ES', type: 'beach', iata: 'SDR' },
  { es: 'San Vicente de la Barquera', en: 'San Vicente de la Barquera', fr: 'San Vicente de la Barquera', de: 'San Vicente de la Barquera', it: 'San Vicente de la Barquera', pt: 'San Vicente de la Barquera', nl: 'San Vicente de la Barquera', country: 'ES', type: 'beach', iata: 'SDR' },
  { es: 'Llanes', en: 'Llanes', fr: 'Llanes', de: 'Llanes', it: 'Llanes', pt: 'Llanes', nl: 'Llanes', country: 'ES', type: 'beach', iata: 'OVD' },
  { es: 'Ribadesella', en: 'Ribadesella', fr: 'Ribadesella', de: 'Ribadesella', it: 'Ribadesella', pt: 'Ribadesella', nl: 'Ribadesella', country: 'ES', type: 'beach', iata: 'OVD' },
  { es: 'Cudillero', en: 'Cudillero', fr: 'Cudillero', de: 'Cudillero', it: 'Cudillero', pt: 'Cudillero', nl: 'Cudillero', country: 'ES', type: 'beach', iata: 'OVD' },
  { es: 'Sanxenxo', en: 'Sanxenxo', fr: 'Sanxenxo', de: 'Sanxenxo', it: 'Sanxenxo', pt: 'Sanxenxo', nl: 'Sanxenxo', country: 'ES', type: 'beach', iata: 'VGO' },
  { es: 'Baiona', en: 'Baiona', fr: 'Baiona', de: 'Baiona', it: 'Baiona', pt: 'Baiona', nl: 'Baiona', country: 'ES', type: 'beach', iata: 'VGO' },
  { es: 'O Grove', en: 'O Grove', fr: 'O Grove', de: 'O Grove', it: 'O Grove', pt: 'O Grove', nl: 'O Grove', country: 'ES', type: 'beach', iata: 'VGO' },
  { es: 'Finisterre', en: 'Finisterre', fr: 'Finisterre', de: 'Finisterre', it: 'Finisterre', pt: 'Finisterre', nl: 'Finisterre', country: 'ES', type: 'beach', iata: 'SCQ' },
  { es: 'Vitoria', en: 'Vitoria-Gasteiz', fr: 'Vitoria-Gasteiz', de: 'Vitoria-Gasteiz', it: 'Vitoria', pt: 'Vitória', nl: 'Vitoria-Gasteiz', country: 'ES', type: 'city', iata: 'VIT' },
  { es: 'Pamplona', en: 'Pamplona', fr: 'Pampelune', de: 'Pamplona', it: 'Pamplona', pt: 'Pamplona', nl: 'Pamplona', country: 'ES', type: 'city', iata: 'PNA' },
  { es: 'Valladolid', en: 'Valladolid', fr: 'Valladolid', de: 'Valladolid', it: 'Valladolid', pt: 'Valladolid', nl: 'Valladolid', country: 'ES', type: 'city', iata: 'VLL' },
  { es: 'León', en: 'León', fr: 'León', de: 'León', it: 'León', pt: 'León', nl: 'León', country: 'ES', type: 'city', iata: 'LEN' },
  { es: 'Burgos', en: 'Burgos', fr: 'Burgos', de: 'Burgos', it: 'Burgos', pt: 'Burgos', nl: 'Burgos', country: 'ES', type: 'city', iata: null },
  { es: 'Logroño', en: 'Logroño', fr: 'Logroño', de: 'Logroño', it: 'Logroño', pt: 'Logroño', nl: 'Logroño', country: 'ES', type: 'city', iata: null },
  { es: 'Badajoz', en: 'Badajoz', fr: 'Badajoz', de: 'Badajoz', it: 'Badajoz', pt: 'Badajoz', nl: 'Badajoz', country: 'ES', type: 'city', iata: 'BJZ' },
  { es: 'Mérida', en: 'Mérida', fr: 'Mérida', de: 'Mérida', it: 'Mérida', pt: 'Mérida', nl: 'Mérida', country: 'ES', type: 'city', iata: null },
  { es: 'Cáceres', en: 'Cáceres', fr: 'Cáceres', de: 'Cáceres', it: 'Cáceres', pt: 'Cáceres', nl: 'Cáceres', country: 'ES', type: 'city', iata: null },
  { es: 'Ávila', en: 'Ávila', fr: 'Ávila', de: 'Ávila', it: 'Ávila', pt: 'Ávila', nl: 'Ávila', country: 'ES', type: 'city', iata: null },
  { es: 'Cuenca', en: 'Cuenca', fr: 'Cuenca', de: 'Cuenca', it: 'Cuenca', pt: 'Cuenca', nl: 'Cuenca', country: 'ES', type: 'mountain', iata: null },
  { es: 'Huesca', en: 'Huesca', fr: 'Huesca', de: 'Huesca', it: 'Huesca', pt: 'Huesca', nl: 'Huesca', country: 'ES', type: 'city', iata: null },
  { es: 'Teruel', en: 'Teruel', fr: 'Teruel', de: 'Teruel', it: 'Teruel', pt: 'Teruel', nl: 'Teruel', country: 'ES', type: 'city', iata: null },
  { es: 'Lleida', en: 'Lleida', fr: 'Lérida', de: 'Lleida', it: 'Lleida', pt: 'Lleida', nl: 'Lleida', country: 'ES', type: 'city', iata: null },
  { es: 'Albacete', en: 'Albacete', fr: 'Albacete', de: 'Albacete', it: 'Albacete', pt: 'Albacete', nl: 'Albacete', country: 'ES', type: 'city', iata: null },
  { es: 'Ciudad Real', en: 'Ciudad Real', fr: 'Ciudad Real', de: 'Ciudad Real', it: 'Ciudad Real', pt: 'Ciudad Real', nl: 'Ciudad Real', country: 'ES', type: 'city', iata: null },
  { es: 'Guadalajara', en: 'Guadalajara', fr: 'Guadalajara', de: 'Guadalajara', it: 'Guadalajara', pt: 'Guadalajara', nl: 'Guadalajara', country: 'ES', type: 'city', iata: null },
  { es: 'Jaén', en: 'Jaén', fr: 'Jaén', de: 'Jaén', it: 'Jaén', pt: 'Jaén', nl: 'Jaén', country: 'ES', type: 'city', iata: null },
  { es: 'Huelva', en: 'Huelva', fr: 'Huelva', de: 'Huelva', it: 'Huelva', pt: 'Huelva', nl: 'Huelva', country: 'ES', type: 'beach', iata: null },
  { es: 'Palencia', en: 'Palencia', fr: 'Palencia', de: 'Palencia', it: 'Palencia', pt: 'Palencia', nl: 'Palencia', country: 'ES', type: 'city', iata: null },
  { es: 'Zamora', en: 'Zamora', fr: 'Zamora', de: 'Zamora', it: 'Zamora', pt: 'Zamora', nl: 'Zamora', country: 'ES', type: 'city', iata: null },
  { es: 'Soria', en: 'Soria', fr: 'Soria', de: 'Soria', it: 'Soria', pt: 'Soria', nl: 'Soria', country: 'ES', type: 'city', iata: null },
  { es: 'Lugo', en: 'Lugo', fr: 'Lugo', de: 'Lugo', it: 'Lugo', pt: 'Lugo', nl: 'Lugo', country: 'ES', type: 'city', iata: null },
  { es: 'Ourense', en: 'Ourense', fr: 'Ourense', de: 'Ourense', it: 'Ourense', pt: 'Ourense', nl: 'Ourense', country: 'ES', type: 'city', iata: null },
  { es: 'Pontevedra', en: 'Pontevedra', fr: 'Pontevedra', de: 'Pontevedra', it: 'Pontevedra', pt: 'Pontevedra', nl: 'Pontevedra', country: 'ES', type: 'city', iata: null },
  { es: 'Ceuta', en: 'Ceuta', fr: 'Ceuta', de: 'Ceuta', it: 'Ceuta', pt: 'Ceuta', nl: 'Ceuta', country: 'ES', type: 'city', iata: null },
  { es: 'Melilla', en: 'Melilla', fr: 'Melilla', de: 'Melilla', it: 'Melilla', pt: 'Melilla', nl: 'Melilla', country: 'ES', type: 'city', iata: 'MLN' },
  { es: 'Úbeda', en: 'Úbeda', fr: 'Úbeda', de: 'Úbeda', it: 'Úbeda', pt: 'Úbeda', nl: 'Úbeda', country: 'ES', type: 'city', iata: null },
  { es: 'Baeza', en: 'Baeza', fr: 'Baeza', de: 'Baeza', it: 'Baeza', pt: 'Baeza', nl: 'Baeza', country: 'ES', type: 'city', iata: null },
  { es: 'Trujillo', en: 'Trujillo', fr: 'Trujillo', de: 'Trujillo', it: 'Trujillo', pt: 'Trujillo', nl: 'Trujillo', country: 'ES', type: 'city', iata: null },
  { es: 'Antequera', en: 'Antequera', fr: 'Antequera', de: 'Antequera', it: 'Antequera', pt: 'Antequera', nl: 'Antequera', country: 'ES', type: 'city', iata: 'AGP' },
  { es: 'Ronda', en: 'Ronda', fr: 'Ronda', de: 'Ronda', it: 'Ronda', pt: 'Ronda', nl: 'Ronda', country: 'ES', type: 'mountain', iata: 'AGP' },
  { es: 'Sierra Nevada', en: 'Sierra Nevada', fr: 'Sierra Nevada', de: 'Sierra Nevada', it: 'Sierra Nevada', pt: 'Sierra Nevada', nl: 'Sierra Nevada', country: 'ES', type: 'mountain', iata: 'GRX' },
  { es: 'Benasque', en: 'Benasque', fr: 'Benasque', de: 'Benasque', it: 'Benasque', pt: 'Benasque', nl: 'Benasque', country: 'ES', type: 'mountain', iata: null },
  { es: 'Jaca', en: 'Jaca', fr: 'Jaca', de: 'Jaca', it: 'Jaca', pt: 'Jaca', nl: 'Jaca', country: 'ES', type: 'mountain', iata: null },
  { es: 'Baqueira Beret', en: 'Baqueira Beret', fr: 'Baqueira Beret', de: 'Baqueira Beret', it: 'Baqueira Beret', pt: 'Baqueira Beret', nl: 'Baqueira Beret', country: 'ES', type: 'mountain', iata: null },
  { es: 'Vielha', en: 'Vielha', fr: 'Vielha', de: 'Vielha', it: 'Vielha', pt: 'Vielha', nl: 'Vielha', country: 'ES', type: 'mountain', iata: null },
  { es: 'Formigal', en: 'Formigal', fr: 'Formigal', de: 'Formigal', it: 'Formigal', pt: 'Formigal', nl: 'Formigal', country: 'ES', type: 'mountain', iata: null },
  { es: 'Aínsa', en: 'Aínsa', fr: 'Aínsa', de: 'Aínsa', it: 'Aínsa', pt: 'Aínsa', nl: 'Aínsa', country: 'ES', type: 'mountain', iata: null },
  { es: 'Cangas de Onís', en: 'Cangas de Onís', fr: 'Cangas de Onís', de: 'Cangas de Onís', it: 'Cangas de Onís', pt: 'Cangas de Onís', nl: 'Cangas de Onís', country: 'ES', type: 'mountain', iata: 'OVD' },
  { es: 'Potes', en: 'Potes', fr: 'Potes', de: 'Potes', it: 'Potes', pt: 'Potes', nl: 'Potes', country: 'ES', type: 'mountain', iata: 'SDR' },
  { es: 'Albarracín', en: 'Albarracín', fr: 'Albarracín', de: 'Albarracín', it: 'Albarracín', pt: 'Albarracín', nl: 'Albarracín', country: 'ES', type: 'mountain', iata: null },
  { es: 'Cazorla', en: 'Cazorla', fr: 'Cazorla', de: 'Cazorla', it: 'Cazorla', pt: 'Cazorla', nl: 'Cazorla', country: 'ES', type: 'mountain', iata: null },
  { es: 'Grazalema', en: 'Grazalema', fr: 'Grazalema', de: 'Grazalema', it: 'Grazalema', pt: 'Grazalema', nl: 'Grazalema', country: 'ES', type: 'mountain', iata: null },
  { es: 'La Alberca', en: 'La Alberca', fr: 'La Alberca', de: 'La Alberca', it: 'La Alberca', pt: 'La Alberca', nl: 'La Alberca', country: 'ES', type: 'mountain', iata: null },
  // Portugal
  { es: 'Lisboa', en: 'Lisbon', fr: 'Lisbonne', de: 'Lissabon', it: 'Lisbona', pt: 'Lisboa', nl: 'Lissabon', country: 'PT', type: 'city', iata: 'LIS' },
  { es: 'Oporto', en: 'Porto', fr: 'Porto', de: 'Porto', it: 'Porto', pt: 'Porto', nl: 'Porto', country: 'PT', type: 'city', iata: 'OPO' },
  { es: 'Faro', en: 'Faro', fr: 'Faro', de: 'Faro', it: 'Faro', pt: 'Faro', nl: 'Faro', country: 'PT', type: 'beach', iata: 'FAO' },
  { es: 'Albufeira', en: 'Albufeira', fr: 'Albufeira', de: 'Albufeira', it: 'Albufeira', pt: 'Albufeira', nl: 'Albufeira', country: 'PT', type: 'beach', iata: 'FAO' },
  { es: 'Lagos', en: 'Lagos', fr: 'Lagos', de: 'Lagos', it: 'Lagos', pt: 'Lagos', nl: 'Lagos', country: 'PT', type: 'beach', iata: 'FAO' },
  { es: 'Portimão', en: 'Portimão', fr: 'Portimão', de: 'Portimão', it: 'Portimão', pt: 'Portimão', nl: 'Portimão', country: 'PT', type: 'beach', iata: 'FAO' },
  { es: 'Vilamoura', en: 'Vilamoura', fr: 'Vilamoura', de: 'Vilamoura', it: 'Vilamoura', pt: 'Vilamoura', nl: 'Vilamoura', country: 'PT', type: 'beach', iata: 'FAO' },
  { es: 'Tavira', en: 'Tavira', fr: 'Tavira', de: 'Tavira', it: 'Tavira', pt: 'Tavira', nl: 'Tavira', country: 'PT', type: 'beach', iata: 'FAO' },
  { es: 'Madeira', en: 'Madeira', fr: 'Madère', de: 'Madeira', it: 'Madera', pt: 'Madeira', nl: 'Madeira', country: 'PT', type: 'island', iata: 'FNC' },
  { es: 'Funchal', en: 'Funchal', fr: 'Funchal', de: 'Funchal', it: 'Funchal', pt: 'Funchal', nl: 'Funchal', country: 'PT', type: 'island', iata: 'FNC' },
  { es: 'Azores', en: 'Azores', fr: 'Açores', de: 'Azoren', it: 'Azzorre', pt: 'Açores', nl: 'Azoren', country: 'PT', type: 'island', iata: 'PDL' },
  { es: 'Sintra', en: 'Sintra', fr: 'Sintra', de: 'Sintra', it: 'Sintra', pt: 'Sintra', nl: 'Sintra', country: 'PT', type: 'city', iata: 'LIS' },
  { es: 'Cascais', en: 'Cascais', fr: 'Cascais', de: 'Cascais', it: 'Cascais', pt: 'Cascais', nl: 'Cascais', country: 'PT', type: 'beach', iata: 'LIS' },
  { es: 'Coimbra', en: 'Coimbra', fr: 'Coimbra', de: 'Coimbra', it: 'Coimbra', pt: 'Coimbra', nl: 'Coimbra', country: 'PT', type: 'city', iata: null },
  { es: 'Braga', en: 'Braga', fr: 'Braga', de: 'Braga', it: 'Braga', pt: 'Braga', nl: 'Braga', country: 'PT', type: 'city', iata: 'OPO' },
  { es: 'Évora', en: 'Évora', fr: 'Évora', de: 'Évora', it: 'Évora', pt: 'Évora', nl: 'Évora', country: 'PT', type: 'city', iata: null },
  { es: 'Nazaré', en: 'Nazaré', fr: 'Nazaré', de: 'Nazaré', it: 'Nazaré', pt: 'Nazaré', nl: 'Nazaré', country: 'PT', type: 'beach', iata: null },
  { es: 'Aveiro', en: 'Aveiro', fr: 'Aveiro', de: 'Aveiro', it: 'Aveiro', pt: 'Aveiro', nl: 'Aveiro', country: 'PT', type: 'city', iata: null },
  // Francia y Mónaco
  { es: 'París', en: 'Paris', fr: 'Paris', de: 'Paris', it: 'Parigi', pt: 'Paris', nl: 'Parijs', country: 'FR', type: 'city', iata: 'CDG' },
  { es: 'Niza', en: 'Nice', fr: 'Nice', de: 'Nizza', it: 'Nizza', pt: 'Nice', nl: 'Nice', country: 'FR', type: 'beach', iata: 'NCE' },
  { es: 'Marsella', en: 'Marseille', fr: 'Marseille', de: 'Marseille', it: 'Marsiglia', pt: 'Marselha', nl: 'Marseille', country: 'FR', type: 'city', iata: 'MRS' },
  { es: 'Lyon', en: 'Lyon', fr: 'Lyon', de: 'Lyon', it: 'Lione', pt: 'Lyon', nl: 'Lyon', country: 'FR', type: 'city', iata: 'LYS' },
  { es: 'Burdeos', en: 'Bordeaux', fr: 'Bordeaux', de: 'Bordeaux', it: 'Bordeaux', pt: 'Bordéus', nl: 'Bordeaux', country: 'FR', type: 'city', iata: 'BOD' },
  { es: 'Toulouse', en: 'Toulouse', fr: 'Toulouse', de: 'Toulouse', it: 'Tolosa', pt: 'Toulouse', nl: 'Toulouse', country: 'FR', type: 'city', iata: 'TLS' },
  { es: 'Estrasburgo', en: 'Strasbourg', fr: 'Strasbourg', de: 'Straßburg', it: 'Strasburgo', pt: 'Estrasburgo', nl: 'Straatsburg', country: 'FR', type: 'city', iata: 'SXB' },
  { es: 'Biarritz', en: 'Biarritz', fr: 'Biarritz', de: 'Biarritz', it: 'Biarritz', pt: 'Biarritz', nl: 'Biarritz', country: 'FR', type: 'beach', iata: 'BIQ' },
  { es: 'Cannes', en: 'Cannes', fr: 'Cannes', de: 'Cannes', it: 'Cannes', pt: 'Cannes', nl: 'Cannes', country: 'FR', type: 'beach', iata: 'NCE' },
  { es: 'Mónaco', en: 'Monaco', fr: 'Monaco', de: 'Monaco', it: 'Monaco', pt: 'Mónaco', nl: 'Monaco', country: 'MC', type: 'city', iata: 'NCE' },
  { es: 'Montpellier', en: 'Montpellier', fr: 'Montpellier', de: 'Montpellier', it: 'Montpellier', pt: 'Montpellier', nl: 'Montpellier', country: 'FR', type: 'city', iata: 'MPL' },
  { es: 'Nantes', en: 'Nantes', fr: 'Nantes', de: 'Nantes', it: 'Nantes', pt: 'Nantes', nl: 'Nantes', country: 'FR', type: 'city', iata: 'NTE' },
  { es: 'Lille', en: 'Lille', fr: 'Lille', de: 'Lille', it: 'Lille', pt: 'Lille', nl: 'Lille', country: 'FR', type: 'city', iata: 'LIL' },
  { es: 'Carcasona', en: 'Carcassonne', fr: 'Carcassonne', de: 'Carcassonne', it: 'Carcassonne', pt: 'Carcassonne', nl: 'Carcassonne', country: 'FR', type: 'city', iata: 'CCF' },
  { es: 'Perpiñán', en: 'Perpignan', fr: 'Perpignan', de: 'Perpignan', it: 'Perpignano', pt: 'Perpignan', nl: 'Perpignan', country: 'FR', type: 'city', iata: 'PGF' },
  { es: 'Aviñón', en: 'Avignon', fr: 'Avignon', de: 'Avignon', it: 'Avignone', pt: 'Avinhão', nl: 'Avignon', country: 'FR', type: 'city', iata: null },
  { es: 'Córcega', en: 'Corsica', fr: 'Corse', de: 'Korsika', it: 'Corsica', pt: 'Córsega', nl: 'Corsica', country: 'FR', type: 'island', iata: 'AJA' },
  { es: 'Lourdes', en: 'Lourdes', fr: 'Lourdes', de: 'Lourdes', it: 'Lourdes', pt: 'Lourdes', nl: 'Lourdes', country: 'FR', type: 'city', iata: 'LDE' },
  { es: 'Mont Saint-Michel', en: 'Mont-Saint-Michel', fr: 'Mont-Saint-Michel', de: 'Mont-Saint-Michel', it: 'Mont-Saint-Michel', pt: 'Monte Saint-Michel', nl: 'Mont-Saint-Michel', country: 'FR', type: 'city', iata: null },
  { es: 'Saint-Tropez', en: 'Saint-Tropez', fr: 'Saint-Tropez', de: 'Saint-Tropez', it: 'Saint-Tropez', pt: 'Saint-Tropez', nl: 'Saint-Tropez', country: 'FR', type: 'beach', iata: null },
  { es: 'Chamonix', en: 'Chamonix-Mont-Blanc', fr: 'Chamonix-Mont-Blanc', de: 'Chamonix-Mont-Blanc', it: 'Chamonix-Mont-Blanc', pt: 'Chamonix-Mont-Blanc', nl: 'Chamonix-Mont-Blanc', country: 'FR', type: 'mountain', iata: null },
  { es: 'Annecy', en: 'Annecy', fr: 'Annecy', de: 'Annecy', it: 'Annecy', pt: 'Annecy', nl: 'Annecy', country: 'FR', type: 'mountain', iata: null },
  // Italia
  { es: 'Roma', en: 'Rome', fr: 'Rome', de: 'Rom', it: 'Roma', pt: 'Roma', nl: 'Rome', country: 'IT', type: 'city', iata: 'FCO' },
  { es: 'Milán', en: 'Milan', fr: 'Milan', de: 'Mailand', it: 'Milano', pt: 'Milão', nl: 'Milaan', country: 'IT', type: 'city', iata: 'MXP' },
  { es: 'Venecia', en: 'Venice', fr: 'Venise', de: 'Venedig', it: 'Venezia', pt: 'Veneza', nl: 'Venetië', country: 'IT', type: 'city', iata: 'VCE' },
  { es: 'Florencia', en: 'Florence', fr: 'Florence', de: 'Florenz', it: 'Firenze', pt: 'Florença', nl: 'Florence', country: 'IT', type: 'city', iata: 'FLR' },
  { es: 'Nápoles', en: 'Naples', fr: 'Naples', de: 'Neapel', it: 'Napoli', pt: 'Nápoles', nl: 'Napels', country: 'IT', type: 'city', iata: 'NAP' },
  { es: 'Bolonia', en: 'Bologna', fr: 'Bologne', de: 'Bologna', it: 'Bologna', pt: 'Bolonha', nl: 'Bologna', country: 'IT', type: 'city', iata: 'BLQ' },
  { es: 'Pisa', en: 'Pisa', fr: 'Pise', de: 'Pisa', it: 'Pisa', pt: 'Pisa', nl: 'Pisa', country: 'IT', type: 'city', iata: 'PSA' },
  { es: 'Turín', en: 'Turin', fr: 'Turin', de: 'Turin', it: 'Torino', pt: 'Turim', nl: 'Turijn', country: 'IT', type: 'city', iata: 'TRN' },
  { es: 'Verona', en: 'Verona', fr: 'Vérone', de: 'Verona', it: 'Verona', pt: 'Verona', nl: 'Verona', country: 'IT', type: 'city', iata: 'VRN' },
  { es: 'Bérgamo', en: 'Bergamo', fr: 'Bergame', de: 'Bergamo', it: 'Bergamo', pt: 'Bérgamo', nl: 'Bergamo', country: 'IT', type: 'city', iata: 'BGY' },
  { es: 'Génova', en: 'Genoa', fr: 'Gênes', de: 'Genua', it: 'Genova', pt: 'Génova', nl: 'Genua', country: 'IT', type: 'city', iata: 'GOA' },
  { es: 'Bari', en: 'Bari', fr: 'Bari', de: 'Bari', it: 'Bari', pt: 'Bari', nl: 'Bari', country: 'IT', type: 'beach', iata: 'BRI' },
  { es: 'Palermo', en: 'Palermo', fr: 'Palerme', de: 'Palermo', it: 'Palermo', pt: 'Palermo', nl: 'Palermo', country: 'IT', type: 'island', iata: 'PMO' },
  { es: 'Catania', en: 'Catania', fr: 'Catane', de: 'Catania', it: 'Catania', pt: 'Catania', nl: 'Catania', country: 'IT', type: 'island', iata: 'CTA' },
  { es: 'Sicilia', en: 'Sicily', fr: 'Sicile', de: 'Sizilien', it: 'Sicilia', pt: 'Sicília', nl: 'Sicilië', country: 'IT', type: 'island', iata: 'CTA' },
  { es: 'Taormina', en: 'Taormina', fr: 'Taormina', de: 'Taormina', it: 'Taormina', pt: 'Taormina', nl: 'Taormina', country: 'IT', type: 'island', iata: 'CTA' },
  { es: 'Cagliari', en: 'Cagliari', fr: 'Cagliari', de: 'Cagliari', it: 'Cagliari', pt: 'Cagliari', nl: 'Cagliari', country: 'IT', type: 'island', iata: 'CAG' },
  { es: 'Cerdeña', en: 'Sardinia', fr: 'Sardaigne', de: 'Sardinien', it: 'Sardegna', pt: 'Sardenha', nl: 'Sardinië', country: 'IT', type: 'island', iata: 'CAG' },
  { es: 'Olbia', en: 'Olbia', fr: 'Olbia', de: 'Olbia', it: 'Olbia', pt: 'Olbia', nl: 'Olbia', country: 'IT', type: 'island', iata: 'OLB' },
  { es: 'Costa Amalfitana', en: 'Amalfi Coast', fr: 'Côte amalfitaine', de: 'Amalfiküste', it: 'Costiera Amalfitana', pt: 'Costa Amalfitana', nl: 'Amalfikust', country: 'IT', type: 'beach', iata: 'NAP' },
  { es: 'Capri', en: 'Capri', fr: 'Capri', de: 'Capri', it: 'Capri', pt: 'Capri', nl: 'Capri', country: 'IT', type: 'island', iata: 'NAP' },
  { es: 'Sorrento', en: 'Sorrento', fr: 'Sorrento', de: 'Sorrento', it: 'Sorrento', pt: 'Sorrento', nl: 'Sorrento', country: 'IT', type: 'beach', iata: 'NAP' },
  { es: 'Lago de Como', en: 'Lake Como', fr: 'Lac de Côme', de: 'Comer See', it: 'Lago di Como', pt: 'Lago de Como', nl: 'Comomeer', country: 'IT', type: 'mountain', iata: 'MXP' },
  { es: 'Lago de Garda', en: 'Lake Garda', fr: 'Lac de Garde', de: 'Gardasee', it: 'Lago di Garda', pt: 'Lago de Garda', nl: 'Gardameer', country: 'IT', type: 'mountain', iata: 'VRN' },
  { es: 'Cinque Terre', en: 'Cinque Terre', fr: 'Cinque Terre', de: 'Cinque Terre', it: 'Cinque Terre', pt: 'Cinque Terre', nl: 'Cinque Terre', country: 'IT', type: 'beach', iata: null },
  { es: 'Siena', en: 'Siena', fr: 'Sienne', de: 'Siena', it: 'Siena', pt: 'Siena', nl: 'Siena', country: 'IT', type: 'city', iata: null },
  { es: 'Rímini', en: 'Rimini', fr: 'Rimini', de: 'Rimini', it: 'Rimini', pt: 'Rimini', nl: 'Rimini', country: 'IT', type: 'beach', iata: 'RMI' },
  { es: 'Dolomitas', en: 'Dolomites', fr: 'Dolomites', de: 'Dolomiten', it: 'Dolomiti', pt: 'Dolomitas', nl: 'Dolomieten', country: 'IT', type: 'mountain', iata: null },
  // Reino Unido e Irlanda
  { es: 'Londres', en: 'London', fr: 'Londres', de: 'London', it: 'Londra', pt: 'Londres', nl: 'Londen', country: 'GB', type: 'city', iata: 'LHR' },
  { es: 'Manchester', en: 'Manchester', fr: 'Manchester', de: 'Manchester', it: 'Manchester', pt: 'Manchester', nl: 'Manchester', country: 'GB', type: 'city', iata: 'MAN' },
  { es: 'Edimburgo', en: 'Edinburgh', fr: 'Édimbourg', de: 'Edinburgh', it: 'Edimburgo', pt: 'Edimburgo', nl: 'Edinburgh', country: 'GB', type: 'city', iata: 'EDI' },
  { es: 'Dublín', en: 'Dublin', fr: 'Dublin', de: 'Dublin', it: 'Dublino', pt: 'Dublin', nl: 'Dublin', country: 'IE', type: 'city', iata: 'DUB' },
  { es: 'Liverpool', en: 'Liverpool', fr: 'Liverpool', de: 'Liverpool', it: 'Liverpool', pt: 'Liverpool', nl: 'Liverpool', country: 'GB', type: 'city', iata: 'LPL' },
  { es: 'Birmingham', en: 'Birmingham', fr: 'Birmingham', de: 'Birmingham', it: 'Birmingham', pt: 'Birmingham', nl: 'Birmingham', country: 'GB', type: 'city', iata: 'BHX' },
  { es: 'Glasgow', en: 'Glasgow', fr: 'Glasgow', de: 'Glasgow', it: 'Glasgow', pt: 'Glasgow', nl: 'Glasgow', country: 'GB', type: 'city', iata: 'GLA' },
  { es: 'Bristol', en: 'Bristol', fr: 'Bristol', de: 'Bristol', it: 'Bristol', pt: 'Bristol', nl: 'Bristol', country: 'GB', type: 'city', iata: 'BRS' },
  { es: 'Newcastle', en: 'Newcastle', fr: 'Newcastle', de: 'Newcastle', it: 'Newcastle', pt: 'Newcastle', nl: 'Newcastle', country: 'GB', type: 'city', iata: 'NCL' },
  { es: 'Leeds', en: 'Leeds', fr: 'Leeds', de: 'Leeds', it: 'Leeds', pt: 'Leeds', nl: 'Leeds', country: 'GB', type: 'city', iata: 'LBA' },
  { es: 'Belfast', en: 'Belfast', fr: 'Belfast', de: 'Belfast', it: 'Belfast', pt: 'Belfast', nl: 'Belfast', country: 'GB', type: 'city', iata: 'BFS' },
  { es: 'Cork', en: 'Cork', fr: 'Cork', de: 'Cork', it: 'Cork', pt: 'Cork', nl: 'Cork', country: 'IE', type: 'city', iata: 'ORK' },
  { es: 'Oxford', en: 'Oxford', fr: 'Oxford', de: 'Oxford', it: 'Oxford', pt: 'Oxford', nl: 'Oxford', country: 'GB', type: 'city', iata: null },
  { es: 'Cambridge', en: 'Cambridge', fr: 'Cambridge', de: 'Cambridge', it: 'Cambridge', pt: 'Cambridge', nl: 'Cambridge', country: 'GB', type: 'city', iata: null },
  // Alemania, Austria y Suiza
  { es: 'Berlín', en: 'Berlin', fr: 'Berlin', de: 'Berlin', it: 'Berlino', pt: 'Berlim', nl: 'Berlijn', country: 'DE', type: 'city', iata: 'BER' },
  { es: 'Múnich', en: 'Munich', fr: 'Munich', de: 'München', it: 'Monaco di Baviera', pt: 'Munique', nl: 'München', country: 'DE', type: 'city', iata: 'MUC' },
  { es: 'Fráncfort', en: 'Frankfurt', fr: 'Francfort', de: 'Frankfurt am Main', it: 'Francoforte', pt: 'Frankfurt', nl: 'Frankfurt', country: 'DE', type: 'city', iata: 'FRA' },
  { es: 'Hamburgo', en: 'Hamburg', fr: 'Hambourg', de: 'Hamburg', it: 'Amburgo', pt: 'Hamburgo', nl: 'Hamburg', country: 'DE', type: 'city', iata: 'HAM' },
  { es: 'Düsseldorf', en: 'Düsseldorf', fr: 'Düsseldorf', de: 'Düsseldorf', it: 'Düsseldorf', pt: 'Düsseldorf', nl: 'Düsseldorf', country: 'DE', type: 'city', iata: 'DUS' },
  { es: 'Colonia', en: 'Cologne', fr: 'Cologne', de: 'Köln', it: 'Colonia', pt: 'Colónia', nl: 'Keulen', country: 'DE', type: 'city', iata: 'CGN' },
  { es: 'Stuttgart', en: 'Stuttgart', fr: 'Stuttgart', de: 'Stuttgart', it: 'Stuttgart', pt: 'Estugarda', nl: 'Stuttgart', country: 'DE', type: 'city', iata: 'STR' },
  { es: 'Dresde', en: 'Dresden', fr: 'Dresde', de: 'Dresden', it: 'Dresda', pt: 'Dresden', nl: 'Dresden', country: 'DE', type: 'city', iata: 'DRS' },
  { es: 'Viena', en: 'Vienna', fr: 'Vienne', de: 'Wien', it: 'Vienna', pt: 'Viena', nl: 'Wenen', country: 'AT', type: 'city', iata: 'VIE' },
  { es: 'Salzburgo', en: 'Salzburg', fr: 'Salzbourg', de: 'Salzburg', it: 'Salisburgo', pt: 'Salzburgo', nl: 'Salzburg', country: 'AT', type: 'city', iata: 'SZG' },
  { es: 'Innsbruck', en: 'Innsbruck', fr: 'Innsbruck', de: 'Innsbruck', it: 'Innsbruck', pt: 'Innsbruck', nl: 'Innsbruck', country: 'AT', type: 'mountain', iata: 'INN' },
  { es: 'Zúrich', en: 'Zurich', fr: 'Zurich', de: 'Zürich', it: 'Zurigo', pt: 'Zurique', nl: 'Zürich', country: 'CH', type: 'city', iata: 'ZRH' },
  { es: 'Ginebra', en: 'Geneva', fr: 'Genève', de: 'Genf', it: 'Ginevra', pt: 'Genebra', nl: 'Genève', country: 'CH', type: 'city', iata: 'GVA' },
  { es: 'Basilea', en: 'Basel', fr: 'Bâle', de: 'Basel', it: 'Basilea', pt: 'Basileia', nl: 'Bazel', country: 'CH', type: 'city', iata: 'BSL' },
  { es: 'Lucerna', en: 'Lucerne', fr: 'Lucerne', de: 'Luzern', it: 'Lucerna', pt: 'Lucerna', nl: 'Luzern', country: 'CH', type: 'city', iata: null },
  { es: 'Interlaken', en: 'Interlaken', fr: 'Interlaken', de: 'Interlaken', it: 'Interlaken', pt: 'Interlaken', nl: 'Interlaken', country: 'CH', type: 'mountain', iata: null },
  { es: 'Zermatt', en: 'Zermatt', fr: 'Zermatt', de: 'Zermatt', it: 'Zermatt', pt: 'Zermatt', nl: 'Zermatt', country: 'CH', type: 'mountain', iata: null },
  // Benelux
  { es: 'Ámsterdam', en: 'Amsterdam', fr: 'Amsterdam', de: 'Amsterdam', it: 'Amsterdam', pt: 'Amesterdão', nl: 'Amsterdam', country: 'NL', type: 'city', iata: 'AMS' },
  { es: 'Bruselas', en: 'Brussels', fr: 'Bruxelles', de: 'Brüssel', it: 'Bruxelles', pt: 'Bruxelas', nl: 'Brussel', country: 'BE', type: 'city', iata: 'BRU' },
  { es: 'Charleroi', en: 'Charleroi', fr: 'Charleroi', de: 'Charleroi', it: 'Charleroi', pt: 'Charleroi', nl: 'Charleroi', country: 'BE', type: 'city', iata: 'CRL' },
  { es: 'Brujas', en: 'Bruges', fr: 'Bruges', de: 'Brügge', it: 'Bruges', pt: 'Bruges', nl: 'Brugge', country: 'BE', type: 'city', iata: null },
  { es: 'Gante', en: 'Ghent', fr: 'Gand', de: 'Gent', it: 'Gand', pt: 'Gante', nl: 'Gent', country: 'BE', type: 'city', iata: null },
  { es: 'Amberes', en: 'Antwerp', fr: 'Anvers', de: 'Antwerpen', it: 'Anversa', pt: 'Antuérpia', nl: 'Antwerpen', country: 'BE', type: 'city', iata: null },
  { es: 'Róterdam', en: 'Rotterdam', fr: 'Rotterdam', de: 'Rotterdam', it: 'Rotterdam', pt: 'Roterdão', nl: 'Rotterdam', country: 'NL', type: 'city', iata: 'RTM' },
  { es: 'La Haya', en: 'The Hague', fr: 'La Haye', de: 'Den Haag', it: 'L\'Aia', pt: 'Haia', nl: 'Den Haag', country: 'NL', type: 'city', iata: null },
  { es: 'Eindhoven', en: 'Eindhoven', fr: 'Eindhoven', de: 'Eindhoven', it: 'Eindhoven', pt: 'Eindhoven', nl: 'Eindhoven', country: 'NL', type: 'city', iata: 'EIN' },
  { es: 'Luxemburgo', en: 'Luxembourg', fr: 'Luxembourg', de: 'Luxemburg', it: 'Lussemburgo', pt: 'Luxemburgo', nl: 'Luxemburg', country: 'LU', type: 'city', iata: 'LUX' },
  // Resto de Europa
  { es: 'Praga', en: 'Prague', fr: 'Prague', de: 'Prag', it: 'Praga', pt: 'Praga', nl: 'Praag', country: 'CZ', type: 'city', iata: 'PRG' },
  { es: 'Budapest', en: 'Budapest', fr: 'Budapest', de: 'Budapest', it: 'Budapest', pt: 'Budapeste', nl: 'Boedapest', country: 'HU', type: 'city', iata: 'BUD' },
  { es: 'Atenas', en: 'Athens', fr: 'Athènes', de: 'Athen', it: 'Atene', pt: 'Atenas', nl: 'Athene', country: 'GR', type: 'city', iata: 'ATH' },
  { es: 'Santorini', en: 'Santorini', fr: 'Santorin', de: 'Santorin', it: 'Santorini', pt: 'Santorini', nl: 'Santorini', country: 'GR', type: 'island', iata: 'JTR' },
  { es: 'Mykonos', en: 'Mykonos', fr: 'Mykonos', de: 'Mykonos', it: 'Mykonos', pt: 'Míconos', nl: 'Mykonos', country: 'GR', type: 'island', iata: 'JMK' },
  { es: 'Creta', en: 'Crete', fr: 'Crète', de: 'Kreta', it: 'Creta', pt: 'Creta', nl: 'Kreta', country: 'GR', type: 'island', iata: 'HER' },
  { es: 'Rodas', en: 'Rhodes', fr: 'Rhodes', de: 'Rhodos', it: 'Rodi', pt: 'Rodes', nl: 'Rodos', country: 'GR', type: 'island', iata: 'RHO' },
  { es: 'Corfú', en: 'Corfu', fr: 'Corfou', de: 'Korfu', it: 'Corfù', pt: 'Corfu', nl: 'Corfu', country: 'GR', type: 'island', iata: 'CFU' },
  { es: 'Dubrovnik', en: 'Dubrovnik', fr: 'Dubrovnik', de: 'Dubrovnik', it: 'Dubrovnik', pt: 'Dubrovnik', nl: 'Dubrovnik', country: 'HR', type: 'beach', iata: 'DBV' },
  { es: 'Split', en: 'Split', fr: 'Split', de: 'Split', it: 'Split', pt: 'Split', nl: 'Split', country: 'HR', type: 'beach', iata: 'SPU' },
  { es: 'Zagreb', en: 'Zagreb', fr: 'Zagreb', de: 'Zagreb', it: 'Zagabria', pt: 'Zagreb', nl: 'Zagreb', country: 'HR', type: 'city', iata: 'ZAG' },
  { es: 'Malta', en: 'Malta', fr: 'Malta', de: 'Malta', it: 'Malta', pt: 'Malta', nl: 'Malta', country: 'MT', type: 'island', iata: 'MLA' },
  { es: 'Chipre', en: 'Cyprus', fr: 'Chypre', de: 'Zypern', it: 'Cipro', pt: 'Chipre', nl: 'Cyprus', country: 'CY', type: 'island', iata: 'LCA' },
  { es: 'Pafos', en: 'Paphos', fr: 'Paphos', de: 'Paphos', it: 'Pafo', pt: 'Pafos', nl: 'Paphos', country: 'CY', type: 'island', iata: 'PFO' },
  { es: 'Estambul', en: 'Istanbul', fr: 'Istanbul', de: 'Istanbul', it: 'Istanbul', pt: 'Istambul', nl: 'Istanboel', country: 'TR', type: 'city', iata: 'IST' },
  { es: 'Antalya', en: 'Antalya', fr: 'Antalya', de: 'Antalya', it: 'Antalya', pt: 'Antalya', nl: 'Antalya', country: 'TR', type: 'beach', iata: 'AYT' },
  { es: 'Bodrum', en: 'Bodrum', fr: 'Bodrum', de: 'Bodrum', it: 'Bodrum', pt: 'Bodrum', nl: 'Bodrum', country: 'TR', type: 'beach', iata: 'BJV' },
  { es: 'Capadocia', en: 'Cappadocia', fr: 'Cappadoce', de: 'Kappadokien', it: 'Cappadocia', pt: 'Capadócia', nl: 'Cappadocië', country: 'TR', type: 'mountain', iata: null },
  { es: 'Copenhague', en: 'Copenhagen', fr: 'Copenhague', de: 'Kopenhagen', it: 'Copenaghen', pt: 'Copenhaga', nl: 'Kopenhagen', country: 'DK', type: 'city', iata: 'CPH' },
  { es: 'Estocolmo', en: 'Stockholm', fr: 'Stockholm', de: 'Stockholm', it: 'Stoccolma', pt: 'Estocolmo', nl: 'Stockholm', country: 'SE', type: 'city', iata: 'ARN' },
  { es: 'Oslo', en: 'Oslo', fr: 'Oslo', de: 'Oslo', it: 'Oslo', pt: 'Oslo', nl: 'Oslo', country: 'NO', type: 'city', iata: 'OSL' },
  { es: 'Bergen', en: 'Bergen', fr: 'Bergen', de: 'Bergen', it: 'Bergen', pt: 'Bergen', nl: 'Bergen', country: 'NO', type: 'city', iata: 'BGO' },
  { es: 'Helsinki', en: 'Helsinki', fr: 'Helsinki', de: 'Helsinki', it: 'Helsinki', pt: 'Helsínquia', nl: 'Helsinki', country: 'FI', type: 'city', iata: 'HEL' },
  { es: 'Rovaniemi', en: 'Rovaniemi', fr: 'Rovaniemi', de: 'Rovaniemi', it: 'Rovaniemi', pt: 'Rovaniemi', nl: 'Rovaniemi', country: 'FI', type: 'mountain', iata: 'RVN' },
  { es: 'Reikiavik', en: 'Reykjavík', fr: 'Reykjavik', de: 'Reykjavík', it: 'Reykjavík', pt: 'Reiquiavique', nl: 'Reykjavik', country: 'IS', type: 'city', iata: 'KEF' },
  { es: 'Varsovia', en: 'Warsaw', fr: 'Varsovie', de: 'Warschau', it: 'Varsavia', pt: 'Varsóvia', nl: 'Warschau', country: 'PL', type: 'city', iata: 'WAW' },
  { es: 'Cracovia', en: 'Kraków', fr: 'Cracovie', de: 'Krakau', it: 'Cracovia', pt: 'Cracóvia', nl: 'Krakau', country: 'PL', type: 'city', iata: 'KRK' },
  { es: 'Gdansk', en: 'Gdańsk', fr: 'Gdańsk', de: 'Danzig', it: 'Danzica', pt: 'Gdańsk', nl: 'Gdańsk', country: 'PL', type: 'city', iata: 'GDN' },
  { es: 'Riga', en: 'Riga', fr: 'Riga', de: 'Riga', it: 'Riga', pt: 'Riga', nl: 'Riga', country: 'LV', type: 'city', iata: 'RIX' },
  { es: 'Tallin', en: 'Tallinn', fr: 'Tallinn', de: 'Tallinn', it: 'Tallinn', pt: 'Tallinn', nl: 'Tallinn', country: 'EE', type: 'city', iata: 'TLL' },
  { es: 'Vilna', en: 'Vilnius', fr: 'Vilnius', de: 'Vilnius', it: 'Vilnius', pt: 'Vílnius', nl: 'Vilnius', country: 'LT', type: 'city', iata: 'VNO' },
  { es: 'Bucarest', en: 'Bucharest', fr: 'Bucarest', de: 'Bukarest', it: 'Bucarest', pt: 'Bucareste', nl: 'Boekarest', country: 'RO', type: 'city', iata: 'OTP' },
  { es: 'Sofía', en: 'Sofia', fr: 'Sofia', de: 'Sofia', it: 'Sofia', pt: 'Sófia', nl: 'Sofia', country: 'BG', type: 'city', iata: 'SOF' },
  { es: 'Belgrado', en: 'Belgrade', fr: 'Belgrade', de: 'Belgrad', it: 'Belgrado', pt: 'Belgrado', nl: 'Belgrado', country: 'RS', type: 'city', iata: 'BEG' },
  { es: 'Liubliana', en: 'Ljubljana', fr: 'Ljubljana', de: 'Ljubljana', it: 'Lubiana', pt: 'Liubliana', nl: 'Ljubljana', country: 'SI', type: 'city', iata: 'LJU' },
  { es: 'Bratislava', en: 'Bratislava', fr: 'Bratislava', de: 'Bratislava', it: 'Bratislava', pt: 'Bratislava', nl: 'Bratislava', country: 'SK', type: 'city', iata: 'BTS' },
  { es: 'Kotor', en: 'Kotor', fr: 'Kotor', de: 'Kotor', it: 'Kotor', pt: 'Kotor', nl: 'Kotor', country: 'ME', type: 'beach', iata: 'TIV' },
  { es: 'Tirana', en: 'Tirana', fr: 'Tirana', de: 'Tirana', it: 'Tirana', pt: 'Tirana', nl: 'Tirana', country: 'AL', type: 'city', iata: 'TIA' },
  { es: 'Gibraltar', en: 'Gibraltar', fr: 'Gibraltar', de: 'Gibraltar', it: 'Gibraltar', pt: 'Gibraltar', nl: 'Gibraltar', country: 'GI', type: 'city', iata: 'GIB' },
  { es: 'Andorra', en: 'Andorra', fr: 'Andorre', de: 'Andorra', it: 'Andorra', pt: 'Andorra', nl: 'Andorra', country: 'AD', type: 'mountain', iata: null },
  // Norte de África y Oriente Medio
  { es: 'Marrakech', en: 'Marrakesh', fr: 'Marrakech', de: 'Marrakesch', it: 'Marrakech', pt: 'Marraquexe', nl: 'Marrakesh', country: 'MA', type: 'city', iata: 'RAK' },
  { es: 'Dubái', en: 'Dubai', fr: 'Dubaï', de: 'Dubai', it: 'Dubai', pt: 'Dubai', nl: 'Dubai', country: 'AE', type: 'city', iata: 'DXB' },
  { es: 'Abu Dabi', en: 'Abu Dhabi', fr: 'Abou Dabi', de: 'Abu Dhabi', it: 'Abu Dhabi', pt: 'Abu Dhabi', nl: 'Abu Dhabi', country: 'AE', type: 'city', iata: 'AUH' },
  { es: 'Doha', en: 'Doha', fr: 'Doha', de: 'Doha', it: 'Doha', pt: 'Doha', nl: 'Doha', country: 'QA', type: 'city', iata: 'DOH' },
  { es: 'El Cairo', en: 'Cairo', fr: 'Le Caire', de: 'Kairo', it: 'Il Cairo', pt: 'Cairo', nl: 'Caïro', country: 'EG', type: 'city', iata: 'CAI' },
  { es: 'Hurghada', en: 'Hurghada', fr: 'Hurghada', de: 'Hurghada', it: 'Hurghada', pt: 'Hurghada', nl: 'Hurghada', country: 'EG', type: 'beach', iata: 'HRG' },
  { es: 'Sharm el-Sheij', en: 'Sharm El Sheikh', fr: 'Charm el-Cheikh', de: 'Scharm El-Scheich', it: 'Sharm el-Sheikh', pt: 'Sharm el-Sheikh', nl: 'Sharm-el-Sheikh', country: 'EG', type: 'beach', iata: 'SSH' },
  { es: 'Tánger', en: 'Tangier', fr: 'Tanger', de: 'Tanger', it: 'Tangeri', pt: 'Tânger', nl: 'Tanger', country: 'MA', type: 'city', iata: 'TNG' },
  { es: 'Fez', en: 'Fez', fr: 'Fès', de: 'Fès', it: 'Fès', pt: 'Fez', nl: 'Fez', country: 'MA', type: 'city', iata: 'FEZ' },
  { es: 'Casablanca', en: 'Casablanca', fr: 'Casablanca', de: 'Casablanca', it: 'Casablanca', pt: 'Casablanca', nl: 'Casablanca', country: 'MA', type: 'city', iata: 'CMN' },
  { es: 'Agadir', en: 'Agadir', fr: 'Agadir', de: 'Agadir', it: 'Agadir', pt: 'Agadir', nl: 'Agadir', country: 'MA', type: 'beach', iata: 'AGA' },
  { es: 'Túnez', en: 'Tunis', fr: 'Tunis', de: 'Tunis', it: 'Tunisi', pt: 'Tunes', nl: 'Tunis', country: 'TN', type: 'city', iata: 'TUN' },
  { es: 'Djerba', en: 'Djerba', fr: 'Djerba', de: 'Djerba', it: 'Djerba', pt: 'Djerba', nl: 'Djerba', country: 'TN', type: 'island', iata: 'DJE' },
  // América
  { es: 'Nueva York', en: 'New York', fr: 'New York', de: 'New York', it: 'New York', pt: 'Nova Iorque', nl: 'New York', country: 'US', type: 'city', iata: 'JFK' },
  { es: 'Miami', en: 'Miami', fr: 'Miami', de: 'Miami', it: 'Miami', pt: 'Miami', nl: 'Miami', country: 'US', type: 'beach', iata: 'MIA' },
  { es: 'Orlando', en: 'Orlando', fr: 'Orlando', de: 'Orlando', it: 'Orlando', pt: 'Orlando', nl: 'Orlando', country: 'US', type: 'city', iata: 'MCO' },
  { es: 'Los Ángeles', en: 'Los Angeles', fr: 'Los Angeles', de: 'Los Angeles', it: 'Los Angeles', pt: 'Los Angeles', nl: 'Los Angeles', country: 'US', type: 'city', iata: 'LAX' },
  { es: 'San Francisco', en: 'San Francisco', fr: 'San Francisco', de: 'San Francisco', it: 'San Francisco', pt: 'São Francisco', nl: 'San Francisco', country: 'US', type: 'city', iata: 'SFO' },
  { es: 'Las Vegas', en: 'Las Vegas', fr: 'Las Vegas', de: 'Las Vegas', it: 'Las Vegas', pt: 'Las Vegas', nl: 'Las Vegas', country: 'US', type: 'city', iata: 'LAS' },
  { es: 'Chicago', en: 'Chicago', fr: 'Chicago', de: 'Chicago', it: 'Chicago', pt: 'Chicago', nl: 'Chicago', country: 'US', type: 'city', iata: 'ORD' },
  { es: 'Boston', en: 'Boston', fr: 'Boston', de: 'Boston', it: 'Boston', pt: 'Boston', nl: 'Boston', country: 'US', type: 'city', iata: 'BOS' },
  { es: 'Washington', en: 'Washington', fr: 'Washington', de: 'Washington', it: 'Washington', pt: 'Washington', nl: 'Washington', country: 'US', type: 'city', iata: 'IAD' },
  { es: 'Toronto', en: 'Toronto', fr: 'Toronto', de: 'Toronto', it: 'Toronto', pt: 'Toronto', nl: 'Toronto', country: 'CA', type: 'city', iata: 'YYZ' },
  { es: 'Montreal', en: 'Montreal', fr: 'Montréal', de: 'Montreal', it: 'Montréal', pt: 'Montreal', nl: 'Montreal', country: 'CA', type: 'city', iata: 'YUL' },
  { es: 'Cancún', en: 'Cancún', fr: 'Cancún', de: 'Cancún', it: 'Cancún', pt: 'Cancún', nl: 'Cancún', country: 'MX', type: 'beach', iata: 'CUN' },
  { es: 'Playa del Carmen', en: 'Playa del Carmen', fr: 'Playa del Carmen', de: 'Playa del Carmen', it: 'Playa del Carmen', pt: 'Playa del Carmen', nl: 'Playa del Carmen', country: 'MX', type: 'beach', iata: 'CUN' },
  { es: 'Riviera Maya', en: 'Riviera Maya', fr: 'Riviera Maya', de: 'Riviera Maya', it: 'Riviera Maya', pt: 'Riviera Maya', nl: 'Riviera Maya', country: 'MX', type: 'beach', iata: 'CUN' },
  { es: 'Ciudad de México', en: 'Mexico City', fr: 'Mexico', de: 'Mexiko-Stadt', it: 'Città del Messico', pt: 'Cidade do México', nl: 'Mexico-Stad', country: 'MX', type: 'city', iata: 'MEX' },
  { es: 'Punta Cana', en: 'Punta Cana', fr: 'Punta Cana', de: 'Punta Cana', it: 'Punta Cana', pt: 'Punta Cana', nl: 'Punta Cana', country: 'DO', type: 'beach', iata: 'PUJ' },
  { es: 'Santo Domingo', en: 'Santo Domingo', fr: 'Santo Domingo', de: 'Santo Domingo', it: 'Santo Domingo', pt: 'São Domingos', nl: 'Santo Domingo', country: 'DO', type: 'city', iata: 'SDQ' },
  { es: 'La Habana', en: 'Havana', fr: 'La Havane', de: 'Havanna', it: 'L\'Avana', pt: 'Havana', nl: 'Havana', country: 'CU', type: 'city', iata: 'HAV' },
  { es: 'Varadero', en: 'Varadero', fr: 'Varadero', de: 'Varadero', it: 'Varadero', pt: 'Varadero', nl: 'Varadero', country: 'CU', type: 'beach', iata: 'VRA' },
  { es: 'San Juan', en: 'San Juan', fr: 'San Juan', de: 'San Juan', it: 'San Juan', pt: 'San Juan', nl: 'San Juan', country: 'PR', type: 'city', iata: 'SJU' },
  { es: 'Buenos Aires', en: 'Buenos Aires', fr: 'Buenos Aires', de: 'Buenos Aires', it: 'Buenos Aires', pt: 'Buenos Aires', nl: 'Buenos Aires', country: 'AR', type: 'city', iata: 'EZE' },
  { es: 'Río de Janeiro', en: 'Rio de Janeiro', fr: 'Rio de Janeiro', de: 'Rio de Janeiro', it: 'Rio de Janeiro', pt: 'Rio de Janeiro', nl: 'Rio de Janeiro', country: 'BR', type: 'city', iata: 'GIG' },
  { es: 'São Paulo', en: 'São Paulo', fr: 'São Paulo', de: 'São Paulo', it: 'São Paulo', pt: 'São Paulo', nl: 'São Paulo', country: 'BR', type: 'city', iata: 'GRU' },
  { es: 'Lima', en: 'Lima', fr: 'Lima', de: 'Lima', it: 'Lima', pt: 'Lima', nl: 'Lima', country: 'PE', type: 'city', iata: 'LIM' },
  { es: 'Cuzco', en: 'Cusco', fr: 'Cuzco', de: 'Cusco', it: 'Cusco', pt: 'Cusco', nl: 'Cuzco', country: 'PE', type: 'mountain', iata: 'CUZ' },
  { es: 'Bogotá', en: 'Bogotá', fr: 'Bogotá', de: 'Bogotá', it: 'Bogotá', pt: 'Bogotá', nl: 'Bogotá', country: 'CO', type: 'city', iata: 'BOG' },
  { es: 'Cartagena de Indias', en: 'Cartagena de Indias', fr: 'Cartagena de Indias', de: 'Cartagena de Indias', it: 'Cartagena de Indias', pt: 'Cartagena de Indias', nl: 'Cartagena de Indias', country: 'CO', type: 'beach', iata: 'CTG' },
  { es: 'Santiago de Chile', en: 'Santiago', fr: 'Santiago du Chili', de: 'Santiago de Chile', it: 'Santiago del Cile', pt: 'Santiago do Chile', nl: 'Santiago', country: 'CL', type: 'city', iata: 'SCL' },
  // Asia, Índico y Oceanía
  { es: 'Tokio', en: 'Tokyo', fr: 'Tokyo', de: 'Tokio', it: 'Tokyo', pt: 'Tóquio', nl: 'Tokio', country: 'JP', type: 'city', iata: 'HND' },
  { es: 'Osaka', en: 'Osaka', fr: 'Osaka', de: 'Osaka', it: 'Osaka', pt: 'Osaka', nl: 'Osaka', country: 'JP', type: 'city', iata: 'KIX' },
  { es: 'Kioto', en: 'Kyoto', fr: 'Kyoto', de: 'Kyoto', it: 'Kyoto', pt: 'Quioto', nl: 'Kyoto', country: 'JP', type: 'city', iata: 'KIX' },
  { es: 'Bangkok', en: 'Bangkok', fr: 'Bangkok', de: 'Bangkok', it: 'Bangkok', pt: 'Banguecoque', nl: 'Bangkok', country: 'TH', type: 'city', iata: 'BKK' },
  { es: 'Phuket', en: 'Phuket', fr: 'Phuket', de: 'Phuket', it: 'Phuket', pt: 'Phuket', nl: 'Phuket', country: 'TH', type: 'island', iata: 'HKT' },
  { es: 'Bali', en: 'Bali', fr: 'Bali', de: 'Bali', it: 'Bali', pt: 'Bali', nl: 'Bali', country: 'ID', type: 'island', iata: 'DPS' },
  { es: 'Maldivas', en: 'Maldives', fr: 'Maldives', de: 'Malediven', it: 'Maldive', pt: 'Maldivas', nl: 'Malediven', country: 'MV', type: 'island', iata: 'MLE' },
  { es: 'Mauricio', en: 'Mauritius', fr: 'Maurice', de: 'Mauritius', it: 'Mauritius', pt: 'Maurícia', nl: 'Mauritius', country: 'MU', type: 'island', iata: 'MRU' },
  { es: 'Singapur', en: 'Singapore', fr: 'Singapour', de: 'Singapur', it: 'Singapore', pt: 'Singapura', nl: 'Singapore', country: 'SG', type: 'city', iata: 'SIN' },
  { es: 'Hong Kong', en: 'Hong Kong', fr: 'Hong Kong', de: 'Hong Kong', it: 'Hong Kong', pt: 'Hong Kong', nl: 'Hong Kong', country: 'HK', type: 'city', iata: 'HKG' },
  { es: 'Pekín', en: 'Beijing', fr: 'Pékin', de: 'Peking', it: 'Pechino', pt: 'Pequim', nl: 'Peking', country: 'CN', type: 'city', iata: 'PEK' },
  { es: 'Shanghái', en: 'Shanghai', fr: 'Shanghai', de: 'Shanghai', it: 'Shanghai', pt: 'Xangai', nl: 'Shanghai', country: 'CN', type: 'city', iata: 'PVG' },
  { es: 'Seúl', en: 'Seoul', fr: 'Séoul', de: 'Seoul', it: 'Seul', pt: 'Seul', nl: 'Seoel', country: 'KR', type: 'city', iata: 'ICN' },
  { es: 'Nueva Delhi', en: 'New Delhi', fr: 'New Delhi', de: 'Neu-Delhi', it: 'Nuova Delhi', pt: 'Nova Deli', nl: 'New Delhi', country: 'IN', type: 'city', iata: 'DEL' },
  { es: 'Hanói', en: 'Hanoi', fr: 'Hanoï', de: 'Hanoi', it: 'Hanoi', pt: 'Hanói', nl: 'Hanoi', country: 'VN', type: 'city', iata: 'HAN' },
  { es: 'Sídney', en: 'Sydney', fr: 'Sydney', de: 'Sydney', it: 'Sydney', pt: 'Sydney', nl: 'Sydney', country: 'AU', type: 'city', iata: 'SYD' },
  { es: 'Melbourne', en: 'Melbourne', fr: 'Melbourne', de: 'Melbourne', it: 'Melbourne', pt: 'Melbourne', nl: 'Melbourne', country: 'AU', type: 'city', iata: 'MEL' },
];

// Rutas de vuelo populares: [IATA origen, IATA destino]. Cada código debe ser el `iata` de alguna ciudad de CITIES.
export const ROUTES = [
  // Domestic Spain
  ['MAD', 'BCN'],
  ['BCN', 'MAD'],
  ['MAD', 'PMI'],
  ['MAD', 'TFN'],
  ['MAD', 'TFS'],
  ['MAD', 'LPA'],
  ['MAD', 'ACE'],
  ['MAD', 'FUE'],
  ['MAD', 'IBZ'],
  ['MAD', 'MAH'],
  ['MAD', 'SPC'],
  ['MAD', 'SCQ'],
  ['MAD', 'VGO'],
  ['MAD', 'LCG'],
  ['MAD', 'OVD'],
  ['MAD', 'BIO'],
  ['MAD', 'XRY'],
  ['MAD', 'MLN'],
  ['BCN', 'PMI'],
  ['BCN', 'IBZ'],
  ['BCN', 'MAH'],
  ['BCN', 'TFN'],
  ['BCN', 'LPA'],
  ['BCN', 'ACE'],
  ['BCN', 'FUE'],
  ['BCN', 'AGP'],
  ['BCN', 'SVQ'],
  ['BCN', 'GRX'],
  ['BCN', 'SCQ'],
  ['BCN', 'VGO'],
  ['BCN', 'LCG'],
  ['BCN', 'OVD'],
  ['BCN', 'BIO'],
  ['VLC', 'PMI'],
  ['VLC', 'IBZ'],
  ['VLC', 'MAH'],
  ['VLC', 'LPA'],
  ['AGP', 'PMI'],
  ['AGP', 'BCN'],
  ['SVQ', 'BCN'],
  ['SVQ', 'PMI'],
  ['BIO', 'PMI'],
  ['BIO', 'SVQ'],
  ['BIO', 'AGP'],
  ['SCQ', 'BCN'],
  ['PMI', 'IBZ'],
  ['PMI', 'MAH'],
  ['LPA', 'TFN'],
  ['LPA', 'ACE'],
  ['LPA', 'FUE'],
  ['TFN', 'SPC'],
  // Spain to Europe
  ['MAD', 'LHR'],
  ['MAD', 'CDG'],
  ['MAD', 'FCO'],
  ['MAD', 'LIS'],
  ['MAD', 'OPO'],
  ['MAD', 'AMS'],
  ['MAD', 'BER'],
  ['MAD', 'FRA'],
  ['MAD', 'MUC'],
  ['MAD', 'BRU'],
  ['MAD', 'ZRH'],
  ['MAD', 'MXP'],
  ['MAD', 'DUB'],
  ['MAD', 'ATH'],
  ['MAD', 'VIE'],
  ['MAD', 'IST'],
  ['MAD', 'RAK'],
  ['MAD', 'DXB'],
  ['BCN', 'LHR'],
  ['BCN', 'CDG'],
  ['BCN', 'FCO'],
  ['BCN', 'AMS'],
  ['BCN', 'LIS'],
  ['BCN', 'BER'],
  ['BCN', 'MXP'],
  ['BCN', 'VCE'],
  ['BCN', 'PRG'],
  ['BCN', 'BUD'],
  ['BCN', 'ATH'],
  ['BCN', 'DUB'],
  ['BCN', 'ZRH'],
  ['BCN', 'OPO'],
  // Europe to Spain
  ['LHR', 'MAD'],
  ['LHR', 'BCN'],
  ['LHR', 'AGP'],
  ['LHR', 'PMI'],
  ['LHR', 'ALC'],
  ['LHR', 'IBZ'],
  ['MAN', 'AGP'],
  ['MAN', 'ALC'],
  ['MAN', 'PMI'],
  ['MAN', 'TFS'],
  ['MAN', 'LPA'],
  ['MAN', 'ACE'],
  ['MAN', 'IBZ'],
  ['MAN', 'FUE'],
  ['BHX', 'AGP'],
  ['BHX', 'ALC'],
  ['EDI', 'AGP'],
  ['EDI', 'ALC'],
  ['DUB', 'AGP'],
  ['DUB', 'ALC'],
  ['DUB', 'PMI'],
  ['DUB', 'TFS'],
  ['DUB', 'LPA'],
  ['DUB', 'ACE'],
  ['DUB', 'BCN'],
  ['DUB', 'MAD'],
  ['CDG', 'MAD'],
  ['CDG', 'BCN'],
  ['CDG', 'AGP'],
  ['CDG', 'PMI'],
  ['CDG', 'SVQ'],
  ['BRU', 'AGP'],
  ['BRU', 'ALC'],
  ['BRU', 'TFS'],
  ['BRU', 'PMI'],
  ['AMS', 'AGP'],
  ['AMS', 'ALC'],
  ['AMS', 'PMI'],
  ['AMS', 'TFS'],
  ['AMS', 'LPA'],
  ['AMS', 'BCN'],
  ['AMS', 'MAD'],
  ['BER', 'PMI'],
  ['BER', 'AGP'],
  ['BER', 'BCN'],
  ['MUC', 'PMI'],
  ['MUC', 'AGP'],
  ['FRA', 'PMI'],
  ['FRA', 'TFS'],
  ['FRA', 'LPA'],
  ['FRA', 'AGP'],
  ['DUS', 'PMI'],
  ['DUS', 'TFS'],
  ['DUS', 'LPA'],
  ['DUS', 'FUE'],
  ['DUS', 'ACE'],
  ['HAM', 'PMI'],
  ['CGN', 'PMI'],
  ['ZRH', 'PMI'],
  ['ZRH', 'AGP'],
  ['ZRH', 'BCN'],
  ['MXP', 'BCN'],
  ['MXP', 'IBZ'],
  ['MXP', 'MAD'],
  ['FCO', 'BCN'],
  ['FCO', 'MAD'],
  ['LIS', 'MAD'],
  ['LIS', 'BCN'],
  ['ARN', 'AGP'],
  ['ARN', 'LPA'],
  ['ARN', 'ALC'],
  ['CPH', 'AGP'],
  ['CPH', 'ALC'],
  ['CPH', 'LPA'],
  ['OSL', 'AGP'],
  ['OSL', 'ALC'],
  ['VIE', 'PMI'],
  // Long-haul
  ['MAD', 'JFK'],
  ['MAD', 'MIA'],
  ['MAD', 'CUN'],
  ['MAD', 'PUJ'],
  ['MAD', 'HAV'],
  ['MAD', 'MEX'],
  ['MAD', 'EZE'],
  ['MAD', 'BOG'],
  ['MAD', 'LIM'],
  ['MAD', 'SCL'],
  ['BCN', 'JFK'],
];
